//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOBOT.BHLImport.BHLImportEFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSSegment
    {
        public BSSegment()
        {
            this.BSSegmentPages = new HashSet<BSSegmentPage>();
        }
    
        public int SegmentID { get; set; }
        public int ItemID { get; set; }
        public string BioStorReferenceID { get; set; }
        public short SequenceOrder { get; set; }
        public string Genre { get; set; }
        public string Title { get; set; }
        public string ContainerTitle { get; set; }
        public string Volume { get; set; }
        public string Series { get; set; }
        public string Issue { get; set; }
        public string Year { get; set; }
        public string Date { get; set; }
        public string ISSN { get; set; }
        public string DOI { get; set; }
        public string StartPageNumber { get; set; }
        public string EndPageNumber { get; set; }
        public Nullable<int> StartPageID { get; set; }
        public Nullable<System.DateTime> ContributorCreationDate { get; set; }
        public Nullable<System.DateTime> ContributorLastModifiedDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> BHLSegmentID { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string PublisherName { get; set; }
        public string PublisherPlace { get; set; }
        public string OCLC { get; set; }
        public string JSTOR { get; set; }
        public string ContributorName { get; set; }
    
        public virtual BSItem BSItem { get; set; }
        public virtual ICollection<BSSegmentPage> BSSegmentPages { get; set; }
    }
}
