//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOBOT.BHLImport.BHLImportEFDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportSource
    {
        public ImportSource()
        {
            this.SegmentAuthors = new HashSet<SegmentAuthor>();
        }
    
        public int ImportSourceID { get; set; }
        public string Source { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual ICollection<SegmentAuthor> SegmentAuthors { get; set; }
    }
}
