
CREATE PROCEDURE [audit].[AuditBasicSelectPrimaryKeyNames]

AS
BEGIN

-- SET NOCOUNT ON added to prevent extra result sets from
-- interfering with SELECT statements.
SET NOCOUNT ON;

SELECT	CCU.TABLE_SCHEMA, CCU.TABLE_NAME, CCU.COLUMN_NAME
FROM	INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU  INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC  
			ON TC.CONSTRAINT_CATALOG = CCU.CONSTRAINT_CATALOG 
			AND TC.CONSTRAINT_SCHEMA = CCU.CONSTRAINT_SCHEMA 
			AND TC.CONSTRAINT_NAME = CCU.CONSTRAINT_NAME 
		INNER JOIN INFORMATION_SCHEMA.COLUMNS C
			ON CCU.TABLE_SCHEMA = C.TABLE_SCHEMA
			AND CCU.TABLE_NAME = C.TABLE_NAME
			AND CCU.COLUMN_NAME = C.COLUMN_NAME
WHERE	TC.CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY
		CCU.TABLE_SCHEMA,
		CCU.TABLE_NAME,
		C.ORDINAL_POSITION

END

