@ECHO OFF

IF "%1" == "" GOTO MISSINGPARAM
IF "%2" == "" GOTO MISSINGPARAM
IF "%~3" == "" GOTO MISSINGPARAM
IF "%4" == "" GOTO MISSINGPARAM
IF "%5" == "" GOTO MISSINGPARAM

@ECHO ON

IF "%~5" == "structure" GOTO CREATEDB
IF "%~5" == "all" GOTO CREATEDB

GOTO DATALOAD

:CREATEDB

REM --------------------------------------
REM  Create Database
REM --------------------------------------
sqlcmd -E -S %1 -Q "CREATE DATABASE [%2]"
sqlcmd -E -S %1 -Q "ALTER DATABASE [%2] MODIFY FILE ( NAME = N'%2', SIZE = 512000KB , FILEGROWTH = 10%)"

REM --------------------------------------
REM  Build Schemas
REM --------------------------------------
sqlcmd -E -S %1 -d %2 -i "Security\Schemas\annotation.sql"
sqlcmd -E -S %1 -d %2 -i "Security\Schemas\audit.sql"
sqlcmd -E -S %1 -d %2 -i "Security\Schemas\import.sql"
sqlcmd -E -S %1 -d %2 -i "Security\Schemas\reqlog.sql"

REM --------------------------------------
REM  Create Full-Text Catalogs
REM --------------------------------------
sqlcmd -E -S %1 -d %2 -i "Storage\BHLSearchCatalog.sql"
sqlcmd -E -S %1 -d %2 -i "Storage\BHLFullTextStopList.sql"
sqlcmd -E -S %1 -d %2 -i "Storage\ftfg_BHLSearchCatalog.sql" -v DatabaseName = "%2"
sqlcmd -E -S %1 -Q "ALTER DATABASE [%2] ADD FILE ( NAME = N'ftrow_BHLSearchCatalog', FILENAME = N'%~3\ftrow_BHLSearchCatalog.ndf' , SIZE = 3072KB , FILEGROWTH = 10%) TO FILEGROUP [ftfg_BHLSearchCatalog]"

REM --------------------------------------
REM  Build Tables
REM --------------------------------------
sqlcmd -E -S %1 -d %2 -i "audit\Tables\AuditBasic.sql"
sqlcmd -E -S %1 -d %2 -i "audit\Tables\AuditBasicSummary.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\User.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Vault.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\APIKey.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\AuthorRole.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\AuthorType.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\BibliographicLevel.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Configuration.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\DOIEntityType.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\DOIStatus.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\EntityCountType.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Identifier.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Institution.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\ItemSource.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\ItemStatus.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Language.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\MonthlyStats.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\NameSource.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\NoteType.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\PageDetailStatus.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\PageNameCount.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\PageType.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\PaginationStatus.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\PDFStatus.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SegmentClusterType.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SegmentGenre.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SegmentStatus.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\TitleAssociationType.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\TitleVariantType.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\ScanningRequest.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\TropicosNames.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\AspNetUsers.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\AspNetRoles.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\AspNetUserClaims.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\AspNetUserLogins.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\AspNetUserRoles.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Author.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\AuthorIdentifier.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\AuthorName.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Collection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\DOI.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\EntityCount.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Keyword.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Title.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\TitleAssociation.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\TitleAssociation_TitleIdentifier.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\TitleAuthor.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\TitleCollection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\TitleKeyword.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\TitleLanguage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\TitleNote.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\TitleVariant.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Title_Identifier.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Item.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\ItemNameFileLog.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\ItemCollection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\ItemLanguage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\TitleItem.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Page.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Page_PageType.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\IndicatedPage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\PageDetail.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\PageIllustration.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\PageFlickr.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Segment.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SegmentAuthor.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SegmentCluster.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SegmentClusterSegment.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SegmentIdentifier.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SegmentKeyword.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SegmentPage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SegmentResolutionLog.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\NameResolved.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Name.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\NameIdentifier.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\NamePage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\NameSegment.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\NamebankEOL.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\MarcImportBatch.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\MarcImportStatus.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\MarcImportError.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\Marc.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\MarcControl.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\MarcDataField.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\MarcSubField.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\DisqusCache.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\PDF.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\PDFPage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SearchCatalog.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SearchCatalogCreator.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SearchCatalogKeyword.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Tables\SearchCatalogSegment.sql"
sqlcmd -E -S %1 -d %2 -i "import\Tables\ImportFileStatus.sql"
sqlcmd -E -S %1 -d %2 -i "import\Tables\ImportRecordStatus.sql"
sqlcmd -E -S %1 -d %2 -i "import\Tables\ImportFile.sql"
sqlcmd -E -S %1 -d %2 -i "import\Tables\ImportRecord.sql"
sqlcmd -E -S %1 -d %2 -i "import\Tables\ImportRecordErrorLog.sql"
sqlcmd -E -S %1 -d %2 -i "import\Tables\ImportRecordCreator.sql"
sqlcmd -E -S %1 -d %2 -i "import\Tables\ImportRecordKeyword.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\Tables\Application.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\Tables\RequestType.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\Tables\RequestLog.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\Tables\RequestLogArchive.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\Tables\RequestHistory.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\Tables\RequestHistoryByTopUsers.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\Tables\RequestHistoryByType.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotatedPageType.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotationKeywordTarget.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotationSource.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotationMarkType.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\Annotation.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotatedTitle.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotatedItem.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotatedPage.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotatedPageCharacteristic.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\PageAnnotation.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotationNote.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotationPolygon.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotationRelation.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotationSubjectCategory.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotationSubject.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotationConcept.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\Annotation_AnnotationConcept.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Tables\AnnotationMark.sql"

REM --------------------------------------
REM  Add Synonyms
REM --------------------------------------
sqlcmd -E -S %1 -d %2 -i "audit\Synonyms\AuditBasicArchive.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Synonyms\MOBOTAdminRequestLog.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Synonyms\MOBOTSecuritySecUserSyn.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Synonyms\TropicosNameReferenceSynonym.sql"

REM --------------------------------------
REM  Build Functions
REM --------------------------------------
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnAssociationStringForTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnAuthorStringForSegment.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnAuthorStringForTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnCOinSAuthorStringForSegment.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnCOinSAuthorStringForTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnCOinSGetFirstAuthorNameForSegment.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnCOinSGetFirstAuthorNameForTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnCOinSGetPageCountForItem.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnCollectionStringForTitleAndItem.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnContainsDiacritic.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnContainsSuspectCharacter.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnFilterString.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnGeographicKeywordStringForTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnGetFullTextSearchString.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnGetIdentifierForSegment.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnGetIdentifierForTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnGetPageCountForSegment.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnIndicatedPageStringForPage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnKeywordStringForSegment.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnKeywordStringForTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnNoteStringForTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnPageTypeStringForPage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnReverseAuthorName.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnSeriesStringForTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnSplitLanguage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnTropicosCheckVolumeExists.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnVariantStringForTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fnVolumeStringForTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Functions\fn_Split.sql"
sqlcmd -E -S %1 -d %2 -i "import\Functions\fnAuthorStringForImportRecord.sql"
sqlcmd -E -S %1 -d %2 -i "import\Functions\fnKeywordStringForImportRecord.sql"

REM --------------------------------------
REM  Build Views
REM --------------------------------------
sqlcmd -E -S %1 -d %2 -i "annotation\Views\vwAnnotation.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Views\vwAnnotationConcept.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Views\ItemCOinSView.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Views\PageDetailView.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Views\PageSummaryView.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Views\SegmentCOinSView.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Views\TitleAuthorView.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Views\TitleKeywordView.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Views\vwMarcControl.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Views\vwMarcDataField.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Views\vwTropicosNames.sql"

REM --------------------------------------
REM  Build Stored Procedures for Auditing
REM --------------------------------------
sqlcmd -E -S %1 -d %2 -i "audit\Stored Procedures\AuditBasicCreateTrigger.sql"
sqlcmd -E -S %1 -d %2 -i "audit\Stored Procedures\AuditBasicCreateAllTriggers.sql"
sqlcmd -E -S %1 -d %2 -i "audit\Stored Procedures\AuditBasicDropTrigger.sql"
sqlcmd -E -S %1 -d %2 -i "audit\Stored Procedures\AuditBasicDropAllTriggers.sql"

REM --------------------------------------
REM  Disable Triggers During Data Load
REM --------------------------------------
sqlcmd -E -S %1 -d %2 -Q "exec audit.AuditBasicDropAllTriggers"

:DATALOAD

IF "%~5" == "data" GOTO INSERTDATA
IF "%~5" == "all" GOTO INSERTDATA

GOTO RESUMESTRUCTURE

:INSERTDATA

REM --------------------------------------
REM  Insert Data
REM --------------------------------------
sqlcmd -E -S %1 -d %2 -i "data\audit.AuditBasic.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\audit.AuditBasicSummary.Table.sql"

sqlcmd -E -S %1 -d %2 -i "data\dbo.AspNetRoles.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.AuthorRole.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.AuthorType.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.BibliographicLevel.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Configuration.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.DOIEntityType.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.DOIStatus.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.EntityCountType.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.ItemSource.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.ItemStatus.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.NameSource.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.NoteType.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.PageType.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.PaginationStatus.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.PDFStatus.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.SegmentClusterType.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.SegmentGenre.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.SegmentStatus.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.TitleAssociationType.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.TitleVariantType.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.TropicosNames.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.User.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Vault.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\import.ImportFileStatus.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\import.ImportRecordStatus.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\reqlog.Application.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\reqlog.RequestType.Table.sql"

sqlcmd -E -S %1 -d %2 -i "data\dbo.AspNetUsers.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.APIKey.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Author.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Institution.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Language.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Collection.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.DOI.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Identifier.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Keyword.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.MonthlyStats.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.NamebankEOL.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.PageDetailStatus.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.ScanningRequest.Table.sql"

sqlcmd -E -S %1 -d %2 -i "data\dbo.AuthorIdentifier.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.AuthorName.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Title.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.TitleAssociation.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.TitleAssociation_TitleIdentifier.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.TitleAuthor.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.TitleCollection.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.TitleKeyword.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.TitleLanguage.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.TitleNote.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.TitleVariant.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Title_Identifier.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Item.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.ItemCollection.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.ItemLanguage.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.ItemNameFileLog.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.TitleItem.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Page.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.PageFlickr.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Page_PageType.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.IndicatedPage.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.PageNameCount.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Segment.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.SegmentAuthor.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.SegmentCluster.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.SegmentClusterSegment.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.SegmentIdentifier.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.SegmentKeyword.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.SegmentPage.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.SegmentResolutionLog.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.PDF.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.PDFPage.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.MarcImportStatus.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.MarcImportBatch.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Marc.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.MarcControl.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.MarcDataField.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.MarcSubField.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.MarcImportError.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.NameResolved.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.Name.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.NameIdentifier.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.NamePage.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\dbo.NameSegment.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\reqlog.RequestLog.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\reqlog.RequestHistory.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\reqlog.RequestHistoryByType.Table.sql"

sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotationSource.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotationMarkType.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotatedPageType.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotatedTitle.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotatedItem.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotatedPage.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotatedPageCharacteristic.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.Annotation.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.PageAnnotation.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotationPolygon.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotationRelation.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotationMark.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotationNote.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotationConcept.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotationKeywordTarget.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotationSubjectCategory.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.AnnotationSubject.Table.sql"
sqlcmd -E -S %1 -d %2 -i "data\annotation.Annotation_AnnotationConcept.Table.sql"

REM --------------------------------------
REM  Populate SearchCatalog Tables
REM --------------------------------------
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SearchCatalogRefresh.sql"
sqlcmd -E -S %1 -d %2 -Q "exec dbo.SearchCatalogRefresh ''"

REM --------------------------------------
REM  Populate EntityCount Table
REM --------------------------------------
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\StatsSelect.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\EntityCountRefresh.sql"
sqlcmd -E -S %1 -d %2 -Q "exec dbo.EntityCountRefresh"

:RESUMESTRUCTURE

IF "%~5" == "structure" GOTO CREATESP
IF "%~5" == "all" GOTO CREATESP

GOTO DONE

:CREATESP

REM --------------------------------------
REM  create Full-Text Indexes
REM --------------------------------------
sqlcmd -E -S %1 -d %2 -i "FullTextIndexes.sql"

REM --------------------------------------
REM  Enable Triggers For Prod Databases
REM --------------------------------------
IF %4 == "true" sqlcmd -E -S %1 -d %2 -Q "exec audit.AuditBasicCreateAllTriggers"

REM --------------------------------------
REM  Build Stored Procedures
REM --------------------------------------
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedItemCheckForSurrogate.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedItemDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedItemInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedItemSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedItemSelectByExternalIdentifer.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedItemUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageCharacteristicDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageCharacteristicDeleteByPageID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageCharacteristicInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageCharacteristicSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageCharacteristicSelectByPageID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageCharacteristicUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageSelectByExternalIdentifer.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageSelectByPageID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageTypeDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageTypeInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageTypeSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageTypeSelectByPageID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageTypeUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedPageUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedTitleDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedTitleInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedTitleSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedTitleSelectByExternalIdentifer.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotatedTitleUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationConceptDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationConceptInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationConceptSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationConceptSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationConceptSelectByCode.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationConceptSelectByConceptText.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationConceptUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationMarkDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationMarkInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationMarkSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationMarkUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationNoteDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationNoteDeleteByAnnotationID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationNoteInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationNoteSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationNoteSelectByAnnotationID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationNoteUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationPolygonDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationPolygonDeleteByAnnotationID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationPolygonInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationPolygonSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationPolygonUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationRelationDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationRelationDeleteByAnnotationID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationRelationInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationRelationSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationRelationSelectByAnnotationID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationRelationUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSelectByExternalIdentifer.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSubjectCategoryDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSubjectCategoryInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSubjectCategorySelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSubjectCategorySelectByCode.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSubjectCategoryUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSubjectDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSubjectDeleteByAnnotationID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSubjectInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSubjectInsertUnique.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSubjectSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSubjectSelectByAnnotationID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSubjectSelectBySubjectText.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationSubjectUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\AnnotationUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\Annotation_AnnotationConceptDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\Annotation_AnnotationConceptDeleteByAnnotationID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\Annotation_AnnotationConceptInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\Annotation_AnnotationConceptSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\Annotation_AnnotationConceptSelectByAnnotationID.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\Annotation_AnnotationConceptUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\GetRelatedPageByExternalIdentifier.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\PageAnnotationDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\PageAnnotationInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\PageAnnotationSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\PageAnnotationUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\SearchPageForConcept.sql"
sqlcmd -E -S %1 -d %2 -i "annotation\Stored Procedures\SearchPageForSubject.sql"
sqlcmd -E -S %1 -d %2 -i "audit\Stored Procedures\AuditBasicArchiveAndSummarize.sql"
sqlcmd -E -S %1 -d %2 -i "audit\Stored Procedures\AuditBasicSelectFromDateToNow.sql"
sqlcmd -E -S %1 -d %2 -i "audit\Stored Procedures\AuditBasicSelectPrimaryKeyNames.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiAuthorSelectBySegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiAuthorSelectByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiAuthorSelectNameStartsWith.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiItemSelectByBarcode.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiItemSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiItemSelectByTitleId.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiItemSelectUnpublished.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\APIKeyDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\APIKeyInsert.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\APIKeyInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiKeySelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\APIKeySelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiKeySelectByEmail.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiKeySelectByKey.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\APIKeyUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiNameResolvedCountUnique.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiNameResolvedCountUniqueBetweenDates.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiNameResolvedListActive.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiNameResolvedListActiveBetweenDates.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiNameResolvedSelectByNameLike.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiNameSegmentSelectBySegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiPageSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiPageSelectByNameBankID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiPageSelectByNameConfirmed.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiPageSelectBySegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiSearchAuthor.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiSearchTitleSimple.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiSegmentIdentifierSelectBySegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiSegmentSelectByAuthor.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiSegmentSelectByDOI.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiSegmentSelectByIdentifier.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiSegmentSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiSegmentSelectByKeyword.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiSegmentSelectRelated.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiSegmentSelectUnpublished.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiTitleIdentifierSelectByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiTitleSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiTitleSelectByAuthor.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiTitleSelectByDOI.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiTitleSelectByIdentifier.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiTitleSelectByKeyword.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiTitleSelectSearchSimple.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiTitleSelectUnpublished.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ApiTitleVariantSelectByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorIdentifierDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorIdentifierInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorIdentifierSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorIdentifierSelectByAuthorID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorIdentifierUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorNameDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorNameInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorNameSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorNameSelectByAuthorID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorNameUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorRoleDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorRoleInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorRoleSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorRoleSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorRoleUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorSelectByInstitution.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorSelectByNameLike.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorSelectByNameLikeAndInstitution.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorSelectByTitleId.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorSelectWithNameByAuthorID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorSelectWithSuspectCharacters.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorTypeDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorTypeInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorTypeSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorTypeSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorTypeUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\AuthorUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\BibliographicLevelDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\BibliographicLevelInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\BibliographicLevelSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\BibliographicLevelSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\BibliographicLevelUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionClearOtherFeatured.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionSelectActive.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionSelectAllForTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionSelectByContents.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionSelectByNameAndAllowedContent.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionSelectByNameLike.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionSelectByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionSelectByUrl.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionSelectFeatured.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\CollectionUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ConfigurationDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ConfigurationInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ConfigurationSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ConfigurationSelectByName.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ConfigurationUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DisqusCacheDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DisqusCacheDeleteByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DisqusCacheInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DisqusCacheSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DisqusCacheSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DisqusCacheUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DOIDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DOIInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DOISelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DOISelectByStatus.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DOISelectSubmitted.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DOISelectValidForSegment.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DOISelectValidForTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DOIStatusSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\DOIUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\EntityCountSelectLatest.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ExportAuthor.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ExportDOI.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ExportIAIdentifiers.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ExportItem.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ExportKeyword.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ExportPage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ExportPageName.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ExportSegment.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ExportSegmentAuthor.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ExportTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ExportTitleIdentifier.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\Find_Text_In_SP.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\IdentifierDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\IdentifierInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\IdentifierSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\IdentifierSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\IdentifierUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\IndicatedPageDeleteAllForPage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\IndicatedPageDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\IndicatedPageInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\IndicatedPageInsertNext.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\IndicatedPageSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\IndicatedPageSelectByPageID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\IndicatedPageUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\InstitutionDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\InstitutionInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\InstitutionSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\InstitutionSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\InstitutionSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\InstitutionSelectDOIStats.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\InstitutionSelectWithPublishedItems.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\InstitutionSelectWithPublishedSegments.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\InstitutionUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemCOinSSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemCOinSSelectByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemCollectionDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemCollectionDeleteForCollection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemCollectionInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemCollectionInsertItemsForCollection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemCollectionSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemCollectionSelectByItem.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemCollectionSelectByItemAndCollection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemCollectionUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemCountByCollection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemCountByInstitution.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemGetNamesXMLByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemLanguageDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemLanguageInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemLanguageSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemLanguageSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemLanguageUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemNameFileLogDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemNameFileLogInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemNameFileLogRefreshSinceDate.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemNameFileLogSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemNameFileLogSelectForCreate.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemNameFileLogSelectForUpload.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemNameFileLogUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectByBarcode.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectByBarCodeOrItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectByCollection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectByCollectionAndStartsWith.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectByInstitution.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectByMARCBibID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectByPageID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectByTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectByTitleId.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectNonMemberMonograph.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectPagination.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectPaginationReport.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectPublished.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectRecent.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectRecentlyChanged.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectWithExpiredPageNames.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectWithoutPageNames.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSelectWithSuspectCharacters.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemSourceSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemStatusDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemStatusInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemStatusSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemStatusSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemStatusUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemUpdateLastPageNameLookupDate.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ItemUpdatePrimaryTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\KeywordDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\KeywordInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\KeywordSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\KeywordSelectByKeyword.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\KeywordSelectCountByInstitution.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\KeywordSelectKeywordByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\KeywordSelectWithSuspectCharacters.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\KeywordUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\LanguageDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\LanguageInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\LanguageSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\LanguageSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\LanguageSelectWithPublishedItems.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\LanguageUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcControlDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcControlInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcControlSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcControlUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcDataFieldDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcDataFieldInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcDataFieldSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcDataFieldUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcImportBatchDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcImportBatchInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcImportBatchSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcImportBatchSelectStatsByInstitution.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcImportBatchUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcResolveTitles.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSelectAssociationIdsByMarcDataFieldID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSelectAssociationsByMarcID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSelectAuthorsByMarcID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSelectForImportByBatchID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSelectFullDetailsForMarcID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSelectPendingImport.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSelectTitleDetailsByMarcID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSelectTitleIdentifiersByMarcID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSelectTitleKeywordsByMarcID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSelectTitleLanguagesByMarcID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSelectTitleNotesByMarcID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSubFieldDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSubFieldInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSubFieldSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcSubFieldUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcUpdateStatusError.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MarcUpdateStatusImported.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MonthlyStatsDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MonthlyStatsInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MonthlyStatsSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MonthlyStatsSelectByDateAndInstitution.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MonthlyStatsSelectByStatType.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MonthlyStatsSelectCurrentMonthSummary.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MonthlyStatsSelectCurrentYearSummary.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MonthlyStatsUpdate.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\MonthlyStatsUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameCountUniqueConfirmed.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameCountUniqueConfirmedBetweenDates.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameIdentifierDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameIdentifierInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameIdentifierSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameIdentifierSelectForResolvedName.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameIdentifierUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameInsertComplete.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameMetadataSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NamePageDelete.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NamePageDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NamePageDeleteByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NamePageInsert.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NamePageInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NamePageSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NamePageSelectByPageID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NamePageSelectByPageIDAndNameString.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NamePageSelectByPageIDAndSource.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NamePageUpdate.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NamePageUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameResolvedDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameResolvedInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameResolvedListActive.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameResolvedListActiveBetweenDates.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameResolvedSearchForPages.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameResolvedSearchForPagesDownload.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameResolvedSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameResolvedSelectByNameLike.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameResolvedSelectByPageID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameResolvedUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameSegmentDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameSegmentInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameSegmentSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameSegmentSelectBySegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameSegmentUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameSelectByNameID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameSelectByNameString.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameSelectByNameStringExact.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameSourceDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameSourceInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameSourceSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameSourceUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NameUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NoteTypeDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NoteTypeInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NoteTypeSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NoteTypeSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\NoteTypeUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OAIIdentifierSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OAIIdentifierSelectItems.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OAIIdentifierSelectPDFs.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OAIIdentifierSelectSegments.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OAIIdentifierSelectTitles.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SearchCatalogCheckStatus.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectByCitationDetail.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectByCitationDetailFT.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectByItem.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectByPageID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectBySegmentDetail.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectBySegmentDetailFT.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectBySegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectByTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectByTitleDetail.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectByTitleDetailFT.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectByTitleIdentifier.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\OpenUrlCitationSelectByDOI.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageDeleteFromItem.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageDetailInsertUpdate.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageDetailSelectForClassifierExport.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageDetailUpdateColor.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageDetailUpdateStatus.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageIllustrationInsert.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageFlickrDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageFlickrInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageFlickrSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageFlickrSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageFlickrSelectByPage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageFlickrSelectRandom.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageFlickrUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageInsertIntoItem.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageMetadataSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageMetadataSelectByPageID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageNameCountUpdate.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageNameDeleteForInactivePages.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageNameSelectByItemIDAndSequence.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageNameSelectByPageIDAndNameFound.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageNameSelectCountByInstitution.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageNameSelectTop.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageResolve.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectByBarCodeAndSequence.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectByItemAndSequence.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectByNameBankID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectCountByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectCurrentUpdateHistory.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectExternalUrlForPageID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectFileNameByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectFirstPageForItem.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectOcrPathForPageID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectWithExpiredPageNamesByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectWithoutPageNames.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSelectWithoutPageNamesByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSummarySelectBarcodeForTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSummarySelectByBarcode.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSummarySelectByBibID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSummarySelectByItemAndSequence.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSummarySelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSummarySelectByItemIDAndTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSummarySelectByPageId.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSummarySelectByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSummarySelectFoldersForTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageSummarySelectForViewerByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageTypeDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageTypeInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageTypeSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageTypeSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageTypeSelectByPageID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageTypeUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PageUpdateLastPageNameLookupDate.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\Page_PageTypeDeleteAllForPage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\Page_PageTypeDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\Page_PageTypeDeleteAutoAssignedImages.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\Page_PageTypeInsert.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\Page_PageTypeInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\Page_PageTypeSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\Page_PageTypeUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PaginationStatusDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PaginationStatusInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PaginationStatusSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PaginationStatusSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PaginationStatusUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFPageDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFPageInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFPageSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFPageSelectForPdfID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFPageSummaryViewSelectByPdfID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFPageUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFSelectDuplicateForPdfID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFSelectForDeletion.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFSelectForFileCreation.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFSelectForWeekAndStatus.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PdfStatsSelectExpanded.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PdfStatsSelectOverview.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFStatusDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFStatusInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFStatusSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFStatusSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFStatusUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFUpdateGenerationInfo.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\PDFUpdatePdfStatus.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ScanningRequestDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ScanningRequestInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ScanningRequestSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\ScanningRequestUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SearchAnnotation.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SearchAuthor.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SearchAuthorComplete.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SearchBook.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SearchBookFT.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SearchBookGlobalFT.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SearchSegment.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SearchSegmentAdvancedFT.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SearchSegmentComplete.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SearchSegmentFT.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SearchTitleKeyword.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentAuthorDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentAuthorInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentAuthorSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentAuthorSelectBySegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentAuthorUpdateAuthorID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentAuthorUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentClusterDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentClusterInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentClusterSegmentDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentClusterSegmentDeleteForSegment.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentClusterSegmentInsert.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentClusterSegmentInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentClusterSegmentSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentClusterSegmentUpdate.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentClusterSegmentUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentClusterSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentClusterUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentCOinSSelectBySegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentGenreDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentGenreInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentGenreSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentGenreSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentGenreUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentIdentifierDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentIdentifierInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentIdentifierSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentIdentifierSelectBySegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentIdentifierUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentKeywordDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentKeywordInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentKeywordSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentKeywordSelectBySegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentKeywordUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentPageDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentPageInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentPageSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentPageSelectBySegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentPageUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentResolutionLogDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentResolutionLogInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentResolutionLogSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentResolutionLogUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectAllBibTeXCitations.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectAllEndNoteCitations.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectBibTeXForSegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectByDateRange.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectByInstitutionAndStartsWith.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectByInstitutionAndStartsWithout.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectByItemID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectByStatusID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectByTitleLike.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectByTitleNotLike.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectEndNoteForSegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectForAuthorID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectForKeyword.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectForSegmentID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectPublished.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectRecentlyClustered.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectRelated.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSelectWithoutSubmittedDOI.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentSimpleSelectByAuthor.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentStatusDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentStatusInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentStatusSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentStatusSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentStatusUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\SegmentUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\StatsSelectForCollection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\StatsSelectForInstitution.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociationDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociationInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociationSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociationSelectByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociationSelectWithSuspectCharacters.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociationTypeDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociationTypeInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociationTypeSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociationTypeSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociationTypeUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociationUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociation_TitleIdentifierDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociation_TitleIdentifierInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociation_TitleIdentifierSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociation_TitleIdentifierSelectByTitleAssociationID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAssociation_TitleIdentifierUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAuthorDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAuthorInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAuthorSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAuthorSelectByTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAuthorUpdateAuthorID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleAuthorUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleBibTeXSelectAllItemCitations.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleBibTeXSelectAllTitleCitations.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleBibTeXSelectForTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleCollectionDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleCollectionDeleteForCollection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleCollectionInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleCollectionInsertTitlesForCollection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleCollectionSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleCollectionSelectByTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleCollectionSelectByTitleAndCollection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleCollectionUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleCountByCollection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleEndNoteSelectAllItemCitations.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleEndNoteSelectAllTitleCitations.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleEndNoteSelectForTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleItemDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleItemInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleItemSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleItemSelectByItem.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleItemSelectByTitle.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleItemUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleItemUpdateItemSequence.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleKeywordDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleKeywordInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleKeywordSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleKeywordSelectByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleKeywordSelectLikeTag.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleKeywordUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleLanguageDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleLanguageInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleLanguageSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleLanguageSelectByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleLanguageUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleNoteDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleNoteInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleNoteSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleNoteSelectByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleNoteUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSearchCount.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSearchPaging.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectByAuthor.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectByBarcode.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectByCollection.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectByCollectionAndStartsWith.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectByDateRangeAndInstitution.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectByInstitution.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectByInstitutionAndStartsWith.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectByInstitutionAndStartsWithout.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectByItem.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectByKeywordInstitutionAndLanguage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectByLanguage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectByNameLike.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectByNameNotLike.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectSearchName.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectWithoutSubmittedDOI.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSelectWithSuspectCharacters.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleSimpleSelectByAuthor.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleVariantDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleVariantInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleVariantSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleVariantSelectByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleVariantTypeSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TitleVariantUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\Title_IdentifierDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\Title_IdentifierInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\Title_IdentifierSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\Title_IdentifierSelectByTitleID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\Title_IdentifierUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\TropicosNamesResolvePage.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\VaultDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\VaultInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\VaultSelectAll.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\VaultSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\VaultSelectMaxID.sql"
sqlcmd -E -S %1 -d %2 -i "dbo\Stored Procedures\VaultUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfiledeleteauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfiledeletebyimportfileid.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfileinsertauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfilepublishtoproduction.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfilerejectfile.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfileselectauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfileselectbyfilename.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfileselectdetails.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfilestatusdeleteauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfilestatusinsertauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfilestatusselectall.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfilestatusselectauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfilestatusupdateauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importfileupdateauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordcreatordeleteauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordcreatorinsertauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordcreatorselectauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordcreatorupdateauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecorddeleteauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecorderrorlogdeleteauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecorderrorloginsertauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecorderrorlogselectauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecorderrorlogupdateauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordinsertauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordkeyworddeleteauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordkeywordinsertauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordkeywordselectauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordkeywordupdateauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordpublishtoproduction.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordselectauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordselectbyimportfileid.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordstatusdeleteauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordstatusinsertauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordstatusselectall.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordstatusselectauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordstatusupdateauto.sql"
sqlcmd -E -S %1 -d %2 -i "import\stored procedures\importrecordupdateauto.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\ApplicationSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestLogArchiveDeleteOld.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestLogMoveRecordsToArchive.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestLogMoveRecordsToHistory.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestHistorySelectByDateRangeAndRequestType.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestLogDeleteAuto.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestLogInsertAuto.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestLogSelectAuto.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestLogUpdateAuto.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestLogSelectDateTotal.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestLogSelectDetails.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestLogSelectHourTotal.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestLogSelectTopIP.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestLogSelectTopUser.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestLogSelectTypesByDate.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\RequestTypeSelectByApplication.sql"
sqlcmd -E -S %1 -d %2 -i "reqlog\stored procedures\DailyTasks.sql"

GOTO DONE

:MISSINGPARAM

@ECHO OFF

ECHO.
ECHO Usage:
ECHO. 
ECHO BHLDBBuildScript SERVERNAME DATABASENAME FULLTEXTCATALOGFILEPATH ISPRODUCTION DATAORSTRUCTURE
ECHO.
ECHO SERVERNAME is the name of the database server
ECHO DATABASENAME is the name of the database to be created
ECHO FULLTEXTCATALOGFILEPATH is the path in which to place the full-text catalog file.  Use quotes around this value if the path contains spaces.
ECHO ISPRODUCTION is true for a production database, and false for a development database.  Auditing triggers are removed from development databases.
ECHO DATAORSTRUCTURE is "structure" to build the empty database (no data), "data" to add data to an existing database, or "all" to build the struture and add the data.
ECHO.
ECHO Example: BHLDBBuildScript localhost BHL "C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA" false all
ECHO.
ECHO It is highly recommended that "BHL" be used as the database name.
ECHO.

@ECHO ON

:DONE

