CREATE TABLE dbo.IDType
(
	IDTypeID INT IDENTITY(1,1) CONSTRAINT PK_IDType PRIMARY KEY NOT NULL,
	IDTypeName nvarchar(50) CONSTRAINT DF_IDType_IdentifierTypeName DEFAULT('') NOT NULL,
	CreationDate DATETIME CONSTRAINT DF_IDType_CreationDate DEFAULT (GETDATE()) NOT NULL,
	LastModifiedDate DATETIME CONSTRAINT DF_IDType_LastModifiedDate DEFAULT (GETDATE()) NOT NULL,
	CreationUserID INT CONSTRAINT DF_IDType_CreationUserID DEFAULT (1) NOT NULL,
	LastModifiedUserID INT CONSTRAINT DF_IDType_LastModifiedUserID  DEFAULT (1) NOT NULL
)
GO
