CREATE TABLE [dbo].[TropicosNames] (
    [NameID]           INT             NOT NULL,
    [FullName]         NVARCHAR (2048) NULL,
    [NameNoAuthors]    NVARCHAR (200)  NOT NULL,
    [Genus]            NVARCHAR (100)  NULL,
    [Subgeneric]       NVARCHAR (151)  NULL,
    [Species]          NVARCHAR (100)  NULL,
    [Subspecific]      NVARCHAR (151)  NULL,
    [Rank]             NVARCHAR (50)   NOT NULL,
    [TropicosTitleID]  INT             NULL,
    [BHLTitleID]       VARCHAR (50)    NOT NULL,
    [AbbreviatedTitle] NVARCHAR (200)  NOT NULL,
    [FullTitle]        NVARCHAR (400)  NULL,
    [Collation]        NVARCHAR (200)  NULL,
    [Volume]           NVARCHAR (100)  NULL,
    [Issue]            NVARCHAR (100)  NULL,
    [Page]             NVARCHAR (100)  NULL,
    [BHLItemID]        INT             NULL,
    [BHLPageID]        INT             NULL,
    [BHLTitle]         NVARCHAR (2000) NULL,
    [BHLVolume]        NVARCHAR (100)  NULL,
    [BHLStartPage]     NVARCHAR (40)   NULL,
    CONSTRAINT [PK_TropicosNames] PRIMARY KEY CLUSTERED ([NameID] ASC, [BHLTitleID] ASC)
);

