//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOBOT.BHL.AdminWeb.BHLImportWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mobot.org/", ConfigurationName="BHLImportWebService.BHLImportWSSoap")]
    public interface BHLImportWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/IAItemSelectPendingApproval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.IAItem[] IAItemSelectPendingApproval(int ageInDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/BotanicusHarvestLogSelectRecent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.BotanicusHarvestLog[] BotanicusHarvestLogSelectRecent(int numLogs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/IAItemErrorSelectRecent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.IAItemError[] IAItemErrorSelectRecent(int numErrors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/ImportErrorSelectRecent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.ImportError[] ImportErrorSelectRecent(int numErrors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/ImportLogSelectRecent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.ImportLog[] ImportLogSelectRecent(int numLogs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/IAItemQueueForDownload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        string[] IAItemQueueForDownload(string iaIdentifier, string localFileFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/IAItemStatusSelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.IAItemStatus[] IAItemStatusSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/IAItemSelectByStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.IAItem[] IAItemSelectByStatus(int itemStatusId, int numberOfRows, int pageNumber, string sortColumn, string sortDirection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/IAItemUpdateStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        string[] IAItemUpdateStatus(int itemId, int itemStatusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/BSItemStatusSelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.BSItemStatus[] BSItemStatusSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/BSItemSelectByStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.BSItem[] BSItemSelectByStatus(int itemStatusId, int numberOfRows, int pageNumber, string sortColumn, string sortDirection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/BSItemUpdateStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        string[] BSItemUpdateStatus(int itemId, int itemStatusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/BSSegmentSelectByItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.BSSegment[] BSSegmentSelectByItem(int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/StatsSelectReadyForProductionBySource", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.Stats[] StatsSelectReadyForProductionBySource(int importSourceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/StatsCountIAItemPendingApproval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.Stats StatsCountIAItemPendingApproval(int ageInDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/StatsSelectIAItemGroupByStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.Stats[] StatsSelectIAItemGroupByStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/StatsSelectIAItemPendingApprovalGroupByAge", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.Stats[] StatsSelectIAItemPendingApprovalGroupByAge(int ageInDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mobot.org/StatsSelectBSItemGroupByStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomObjectBase))]
        MOBOT.BHL.AdminWeb.BHLImportWebService.Stats[] StatsSelectBSItemGroupByStatus();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class IAItem : @__IAItem {
        
        private int totalItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalItems {
            get {
                return this.totalItemsField;
            }
            set {
                this.totalItemsField = value;
                this.RaisePropertyChanged("TotalItems");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IAItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__IAItem : CustomObjectBase {
        
        private int itemIDField;
        
        private int itemStatusIDField;
        
        private string localFileFolderField;
        
        private string iAIdentifierPrefixField;
        
        private string iAIdentifierField;
        
        private string sponsorField;
        
        private string sponsorNameField;
        
        private string sponsorDateField;
        
        private string scanningCenterField;
        
        private string callNumberField;
        
        private System.Nullable<int> imageCountField;
        
        private string identifierAccessUrlField;
        
        private string volumeField;
        
        private string noteField;
        
        private string scanOperatorField;
        
        private string scanDateField;
        
        private string externalStatusField;
        
        private string titleIDField;
        
        private string yearField;
        
        private string identifierBibField;
        
        private string zQueryField;
        
        private string mARCBibIDField;
        
        private string licenseUrlField;
        
        private string rightsField;
        
        private string dueDiligenceField;
        
        private string possibleCopyrightStatusField;
        
        private string copyrightRegionField;
        
        private string copyrightCommentField;
        
        private string copyrightEvidenceField;
        
        private string copyrightEvidenceOperatorField;
        
        private string copyrightEvidenceDateField;
        
        private string shortTitleField;
        
        private string barCodeField;
        
        private System.Nullable<System.DateTime> iADateStampField;
        
        private System.Nullable<System.DateTime> iAAddedDateField;
        
        private System.Nullable<System.DateTime> lastOAIDataHarvestDateField;
        
        private System.Nullable<System.DateTime> lastXMLDataHarvestDateField;
        
        private System.Nullable<System.DateTime> lastProductionDateField;
        
        private byte noMARCOkField;
        
        private System.DateTime createdDateField;
        
        private System.DateTime lastModifiedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
                this.RaisePropertyChanged("ItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ItemStatusID {
            get {
                return this.itemStatusIDField;
            }
            set {
                this.itemStatusIDField = value;
                this.RaisePropertyChanged("ItemStatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LocalFileFolder {
            get {
                return this.localFileFolderField;
            }
            set {
                this.localFileFolderField = value;
                this.RaisePropertyChanged("LocalFileFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IAIdentifierPrefix {
            get {
                return this.iAIdentifierPrefixField;
            }
            set {
                this.iAIdentifierPrefixField = value;
                this.RaisePropertyChanged("IAIdentifierPrefix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string IAIdentifier {
            get {
                return this.iAIdentifierField;
            }
            set {
                this.iAIdentifierField = value;
                this.RaisePropertyChanged("IAIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sponsor {
            get {
                return this.sponsorField;
            }
            set {
                this.sponsorField = value;
                this.RaisePropertyChanged("Sponsor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SponsorName {
            get {
                return this.sponsorNameField;
            }
            set {
                this.sponsorNameField = value;
                this.RaisePropertyChanged("SponsorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SponsorDate {
            get {
                return this.sponsorDateField;
            }
            set {
                this.sponsorDateField = value;
                this.RaisePropertyChanged("SponsorDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ScanningCenter {
            get {
                return this.scanningCenterField;
            }
            set {
                this.scanningCenterField = value;
                this.RaisePropertyChanged("ScanningCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CallNumber {
            get {
                return this.callNumberField;
            }
            set {
                this.callNumberField = value;
                this.RaisePropertyChanged("CallNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> ImageCount {
            get {
                return this.imageCountField;
            }
            set {
                this.imageCountField = value;
                this.RaisePropertyChanged("ImageCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string IdentifierAccessUrl {
            get {
                return this.identifierAccessUrlField;
            }
            set {
                this.identifierAccessUrlField = value;
                this.RaisePropertyChanged("IdentifierAccessUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
                this.RaisePropertyChanged("Volume");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ScanOperator {
            get {
                return this.scanOperatorField;
            }
            set {
                this.scanOperatorField = value;
                this.RaisePropertyChanged("ScanOperator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ScanDate {
            get {
                return this.scanDateField;
            }
            set {
                this.scanDateField = value;
                this.RaisePropertyChanged("ScanDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ExternalStatus {
            get {
                return this.externalStatusField;
            }
            set {
                this.externalStatusField = value;
                this.RaisePropertyChanged("ExternalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string TitleID {
            get {
                return this.titleIDField;
            }
            set {
                this.titleIDField = value;
                this.RaisePropertyChanged("TitleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string IdentifierBib {
            get {
                return this.identifierBibField;
            }
            set {
                this.identifierBibField = value;
                this.RaisePropertyChanged("IdentifierBib");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ZQuery {
            get {
                return this.zQueryField;
            }
            set {
                this.zQueryField = value;
                this.RaisePropertyChanged("ZQuery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string MARCBibID {
            get {
                return this.mARCBibIDField;
            }
            set {
                this.mARCBibIDField = value;
                this.RaisePropertyChanged("MARCBibID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string LicenseUrl {
            get {
                return this.licenseUrlField;
            }
            set {
                this.licenseUrlField = value;
                this.RaisePropertyChanged("LicenseUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Rights {
            get {
                return this.rightsField;
            }
            set {
                this.rightsField = value;
                this.RaisePropertyChanged("Rights");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string DueDiligence {
            get {
                return this.dueDiligenceField;
            }
            set {
                this.dueDiligenceField = value;
                this.RaisePropertyChanged("DueDiligence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string PossibleCopyrightStatus {
            get {
                return this.possibleCopyrightStatusField;
            }
            set {
                this.possibleCopyrightStatusField = value;
                this.RaisePropertyChanged("PossibleCopyrightStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string CopyrightRegion {
            get {
                return this.copyrightRegionField;
            }
            set {
                this.copyrightRegionField = value;
                this.RaisePropertyChanged("CopyrightRegion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string CopyrightComment {
            get {
                return this.copyrightCommentField;
            }
            set {
                this.copyrightCommentField = value;
                this.RaisePropertyChanged("CopyrightComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string CopyrightEvidence {
            get {
                return this.copyrightEvidenceField;
            }
            set {
                this.copyrightEvidenceField = value;
                this.RaisePropertyChanged("CopyrightEvidence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string CopyrightEvidenceOperator {
            get {
                return this.copyrightEvidenceOperatorField;
            }
            set {
                this.copyrightEvidenceOperatorField = value;
                this.RaisePropertyChanged("CopyrightEvidenceOperator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string CopyrightEvidenceDate {
            get {
                return this.copyrightEvidenceDateField;
            }
            set {
                this.copyrightEvidenceDateField = value;
                this.RaisePropertyChanged("CopyrightEvidenceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string ShortTitle {
            get {
                return this.shortTitleField;
            }
            set {
                this.shortTitleField = value;
                this.RaisePropertyChanged("ShortTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string BarCode {
            get {
                return this.barCodeField;
            }
            set {
                this.barCodeField = value;
                this.RaisePropertyChanged("BarCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<System.DateTime> IADateStamp {
            get {
                return this.iADateStampField;
            }
            set {
                this.iADateStampField = value;
                this.RaisePropertyChanged("IADateStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<System.DateTime> IAAddedDate {
            get {
                return this.iAAddedDateField;
            }
            set {
                this.iAAddedDateField = value;
                this.RaisePropertyChanged("IAAddedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<System.DateTime> LastOAIDataHarvestDate {
            get {
                return this.lastOAIDataHarvestDateField;
            }
            set {
                this.lastOAIDataHarvestDateField = value;
                this.RaisePropertyChanged("LastOAIDataHarvestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public System.Nullable<System.DateTime> LastXMLDataHarvestDate {
            get {
                return this.lastXMLDataHarvestDateField;
            }
            set {
                this.lastXMLDataHarvestDateField = value;
                this.RaisePropertyChanged("LastXMLDataHarvestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public System.Nullable<System.DateTime> LastProductionDate {
            get {
                return this.lastProductionDateField;
            }
            set {
                this.lastProductionDateField = value;
                this.RaisePropertyChanged("LastProductionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public byte NoMARCOk {
            get {
                return this.noMARCOkField;
            }
            set {
                this.noMARCOkField = value;
                this.RaisePropertyChanged("NoMARCOk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("CreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public System.DateTime LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__BSSegment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BSSegment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__BSItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BSItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__BSItemStatus))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BSItemStatus))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__IAItemStatus))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IAItemStatus))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__ImportLog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportLog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__ImportError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__IAItemError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IAItemError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__BotanicusHarvestLog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BotanicusHarvestLog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@__IAItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IAItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class CustomObjectBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class Stats : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int numberOfItemsField;
        
        private int ageInDaysField;
        
        private int itemStatusIDField;
        
        private string statusField;
        
        private string descriptionField;
        
        private string sourceField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int NumberOfItems {
            get {
                return this.numberOfItemsField;
            }
            set {
                this.numberOfItemsField = value;
                this.RaisePropertyChanged("NumberOfItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int AgeInDays {
            get {
                return this.ageInDaysField;
            }
            set {
                this.ageInDaysField = value;
                this.RaisePropertyChanged("AgeInDays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ItemStatusID {
            get {
                return this.itemStatusIDField;
            }
            set {
                this.itemStatusIDField = value;
                this.RaisePropertyChanged("ItemStatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BSSegment))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__BSSegment : CustomObjectBase {
        
        private int segmentIDField;
        
        private int itemIDField;
        
        private string bioStorReferenceIDField;
        
        private short sequenceOrderField;
        
        private string genreField;
        
        private string titleField;
        
        private string containerTitleField;
        
        private string volumeField;
        
        private string seriesField;
        
        private string issueField;
        
        private string yearField;
        
        private string dateField;
        
        private string iSSNField;
        
        private string dOIField;
        
        private string startPageNumberField;
        
        private string endPageNumberField;
        
        private System.Nullable<int> startPageIDField;
        
        private System.Nullable<System.DateTime> contributorCreationDateField;
        
        private System.Nullable<System.DateTime> contributorLastModifiedDateField;
        
        private System.Nullable<int> bHLSegmentIDField;
        
        private System.DateTime creationDateField;
        
        private System.DateTime lastModifiedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SegmentID {
            get {
                return this.segmentIDField;
            }
            set {
                this.segmentIDField = value;
                this.RaisePropertyChanged("SegmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
                this.RaisePropertyChanged("ItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BioStorReferenceID {
            get {
                return this.bioStorReferenceIDField;
            }
            set {
                this.bioStorReferenceIDField = value;
                this.RaisePropertyChanged("BioStorReferenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short SequenceOrder {
            get {
                return this.sequenceOrderField;
            }
            set {
                this.sequenceOrderField = value;
                this.RaisePropertyChanged("SequenceOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Genre {
            get {
                return this.genreField;
            }
            set {
                this.genreField = value;
                this.RaisePropertyChanged("Genre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ContainerTitle {
            get {
                return this.containerTitleField;
            }
            set {
                this.containerTitleField = value;
                this.RaisePropertyChanged("ContainerTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
                this.RaisePropertyChanged("Volume");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
                this.RaisePropertyChanged("Series");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Issue {
            get {
                return this.issueField;
            }
            set {
                this.issueField = value;
                this.RaisePropertyChanged("Issue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ISSN {
            get {
                return this.iSSNField;
            }
            set {
                this.iSSNField = value;
                this.RaisePropertyChanged("ISSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DOI {
            get {
                return this.dOIField;
            }
            set {
                this.dOIField = value;
                this.RaisePropertyChanged("DOI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string StartPageNumber {
            get {
                return this.startPageNumberField;
            }
            set {
                this.startPageNumberField = value;
                this.RaisePropertyChanged("StartPageNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string EndPageNumber {
            get {
                return this.endPageNumberField;
            }
            set {
                this.endPageNumberField = value;
                this.RaisePropertyChanged("EndPageNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<int> StartPageID {
            get {
                return this.startPageIDField;
            }
            set {
                this.startPageIDField = value;
                this.RaisePropertyChanged("StartPageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<System.DateTime> ContributorCreationDate {
            get {
                return this.contributorCreationDateField;
            }
            set {
                this.contributorCreationDateField = value;
                this.RaisePropertyChanged("ContributorCreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<System.DateTime> ContributorLastModifiedDate {
            get {
                return this.contributorLastModifiedDateField;
            }
            set {
                this.contributorLastModifiedDateField = value;
                this.RaisePropertyChanged("ContributorLastModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<int> BHLSegmentID {
            get {
                return this.bHLSegmentIDField;
            }
            set {
                this.bHLSegmentIDField = value;
                this.RaisePropertyChanged("BHLSegmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public System.DateTime LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class BSSegment : @__BSSegment {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BSItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__BSItem : CustomObjectBase {
        
        private int itemIDField;
        
        private System.Nullable<int> bHLItemIDField;
        
        private int itemStatusIDField;
        
        private System.DateTime creationDateField;
        
        private System.DateTime lastModifiedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
                this.RaisePropertyChanged("ItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> BHLItemID {
            get {
                return this.bHLItemIDField;
            }
            set {
                this.bHLItemIDField = value;
                this.RaisePropertyChanged("BHLItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ItemStatusID {
            get {
                return this.itemStatusIDField;
            }
            set {
                this.itemStatusIDField = value;
                this.RaisePropertyChanged("ItemStatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class BSItem : @__BSItem {
        
        private string titleField;
        
        private string volumeField;
        
        private int totalSegmentsField;
        
        private int totalItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
                this.RaisePropertyChanged("Volume");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TotalSegments {
            get {
                return this.totalSegmentsField;
            }
            set {
                this.totalSegmentsField = value;
                this.RaisePropertyChanged("TotalSegments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int TotalItems {
            get {
                return this.totalItemsField;
            }
            set {
                this.totalItemsField = value;
                this.RaisePropertyChanged("TotalItems");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BSItemStatus))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__BSItemStatus : CustomObjectBase {
        
        private int itemStatusIDField;
        
        private string statusField;
        
        private string descriptionField;
        
        private System.DateTime creationDateField;
        
        private System.DateTime lastModifiedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ItemStatusID {
            get {
                return this.itemStatusIDField;
            }
            set {
                this.itemStatusIDField = value;
                this.RaisePropertyChanged("ItemStatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class BSItemStatus : @__BSItemStatus {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IAItemStatus))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__IAItemStatus : CustomObjectBase {
        
        private int itemStatusIDField;
        
        private string statusField;
        
        private string descriptionField;
        
        private System.DateTime createdDateField;
        
        private System.DateTime lastModifiedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ItemStatusID {
            get {
                return this.itemStatusIDField;
            }
            set {
                this.itemStatusIDField = value;
                this.RaisePropertyChanged("ItemStatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("CreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class IAItemStatus : @__IAItemStatus {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportLog))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__ImportLog : CustomObjectBase {
        
        private int importLogIDField;
        
        private System.DateTime importDateField;
        
        private System.Nullable<int> importSourceIDField;
        
        private string barCodeField;
        
        private string importResultField;
        
        private int titleInsertField;
        
        private int titleUpdateField;
        
        private int creatorInsertField;
        
        private int creatorUpdateField;
        
        private int titleCreatorInsertField;
        
        private int titleCreatorUpdateField;
        
        private int titleTagInsertField;
        
        private int titleTagUpdateField;
        
        private System.Nullable<int> titleTitleIdentifierInsertField;
        
        private System.Nullable<int> titleTitleIdentifierUpdateField;
        
        private System.Nullable<int> titleAssociationInsertField;
        
        private System.Nullable<int> titleAssociationTitleIdentifierInsertField;
        
        private System.Nullable<int> titleVariantInsertField;
        
        private int itemInsertField;
        
        private int itemUpdateField;
        
        private System.Nullable<int> titleItemInsertField;
        
        private int pageInsertField;
        
        private int pageUpdateField;
        
        private int indicatedPageInsertField;
        
        private int indicatedPageUpdateField;
        
        private int pagePageTypeInsertField;
        
        private int pagePageTypeUpdateField;
        
        private int pageNameInsertField;
        
        private int pageNameUpdateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ImportLogID {
            get {
                return this.importLogIDField;
            }
            set {
                this.importLogIDField = value;
                this.RaisePropertyChanged("ImportLogID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ImportDate {
            get {
                return this.importDateField;
            }
            set {
                this.importDateField = value;
                this.RaisePropertyChanged("ImportDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> ImportSourceID {
            get {
                return this.importSourceIDField;
            }
            set {
                this.importSourceIDField = value;
                this.RaisePropertyChanged("ImportSourceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BarCode {
            get {
                return this.barCodeField;
            }
            set {
                this.barCodeField = value;
                this.RaisePropertyChanged("BarCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ImportResult {
            get {
                return this.importResultField;
            }
            set {
                this.importResultField = value;
                this.RaisePropertyChanged("ImportResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TitleInsert {
            get {
                return this.titleInsertField;
            }
            set {
                this.titleInsertField = value;
                this.RaisePropertyChanged("TitleInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int TitleUpdate {
            get {
                return this.titleUpdateField;
            }
            set {
                this.titleUpdateField = value;
                this.RaisePropertyChanged("TitleUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int CreatorInsert {
            get {
                return this.creatorInsertField;
            }
            set {
                this.creatorInsertField = value;
                this.RaisePropertyChanged("CreatorInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int CreatorUpdate {
            get {
                return this.creatorUpdateField;
            }
            set {
                this.creatorUpdateField = value;
                this.RaisePropertyChanged("CreatorUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int TitleCreatorInsert {
            get {
                return this.titleCreatorInsertField;
            }
            set {
                this.titleCreatorInsertField = value;
                this.RaisePropertyChanged("TitleCreatorInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int TitleCreatorUpdate {
            get {
                return this.titleCreatorUpdateField;
            }
            set {
                this.titleCreatorUpdateField = value;
                this.RaisePropertyChanged("TitleCreatorUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int TitleTagInsert {
            get {
                return this.titleTagInsertField;
            }
            set {
                this.titleTagInsertField = value;
                this.RaisePropertyChanged("TitleTagInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int TitleTagUpdate {
            get {
                return this.titleTagUpdateField;
            }
            set {
                this.titleTagUpdateField = value;
                this.RaisePropertyChanged("TitleTagUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> TitleTitleIdentifierInsert {
            get {
                return this.titleTitleIdentifierInsertField;
            }
            set {
                this.titleTitleIdentifierInsertField = value;
                this.RaisePropertyChanged("TitleTitleIdentifierInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> TitleTitleIdentifierUpdate {
            get {
                return this.titleTitleIdentifierUpdateField;
            }
            set {
                this.titleTitleIdentifierUpdateField = value;
                this.RaisePropertyChanged("TitleTitleIdentifierUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<int> TitleAssociationInsert {
            get {
                return this.titleAssociationInsertField;
            }
            set {
                this.titleAssociationInsertField = value;
                this.RaisePropertyChanged("TitleAssociationInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<int> TitleAssociationTitleIdentifierInsert {
            get {
                return this.titleAssociationTitleIdentifierInsertField;
            }
            set {
                this.titleAssociationTitleIdentifierInsertField = value;
                this.RaisePropertyChanged("TitleAssociationTitleIdentifierInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<int> TitleVariantInsert {
            get {
                return this.titleVariantInsertField;
            }
            set {
                this.titleVariantInsertField = value;
                this.RaisePropertyChanged("TitleVariantInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int ItemInsert {
            get {
                return this.itemInsertField;
            }
            set {
                this.itemInsertField = value;
                this.RaisePropertyChanged("ItemInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int ItemUpdate {
            get {
                return this.itemUpdateField;
            }
            set {
                this.itemUpdateField = value;
                this.RaisePropertyChanged("ItemUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<int> TitleItemInsert {
            get {
                return this.titleItemInsertField;
            }
            set {
                this.titleItemInsertField = value;
                this.RaisePropertyChanged("TitleItemInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int PageInsert {
            get {
                return this.pageInsertField;
            }
            set {
                this.pageInsertField = value;
                this.RaisePropertyChanged("PageInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int PageUpdate {
            get {
                return this.pageUpdateField;
            }
            set {
                this.pageUpdateField = value;
                this.RaisePropertyChanged("PageUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int IndicatedPageInsert {
            get {
                return this.indicatedPageInsertField;
            }
            set {
                this.indicatedPageInsertField = value;
                this.RaisePropertyChanged("IndicatedPageInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int IndicatedPageUpdate {
            get {
                return this.indicatedPageUpdateField;
            }
            set {
                this.indicatedPageUpdateField = value;
                this.RaisePropertyChanged("IndicatedPageUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int PagePageTypeInsert {
            get {
                return this.pagePageTypeInsertField;
            }
            set {
                this.pagePageTypeInsertField = value;
                this.RaisePropertyChanged("PagePageTypeInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int PagePageTypeUpdate {
            get {
                return this.pagePageTypeUpdateField;
            }
            set {
                this.pagePageTypeUpdateField = value;
                this.RaisePropertyChanged("PagePageTypeUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int PageNameInsert {
            get {
                return this.pageNameInsertField;
            }
            set {
                this.pageNameInsertField = value;
                this.RaisePropertyChanged("PageNameInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int PageNameUpdate {
            get {
                return this.pageNameUpdateField;
            }
            set {
                this.pageNameUpdateField = value;
                this.RaisePropertyChanged("PageNameUpdate");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class ImportLog : @__ImportLog {
        
        private string importSourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ImportSource {
            get {
                return this.importSourceField;
            }
            set {
                this.importSourceField = value;
                this.RaisePropertyChanged("ImportSource");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportError))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__ImportError : CustomObjectBase {
        
        private int importErrorIDField;
        
        private string keyTypeField;
        
        private string keyValueField;
        
        private System.DateTime errorDateField;
        
        private System.Nullable<int> numberField;
        
        private System.Nullable<int> severityField;
        
        private System.Nullable<int> stateField;
        
        private string procedureField;
        
        private System.Nullable<int> lineField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ImportErrorID {
            get {
                return this.importErrorIDField;
            }
            set {
                this.importErrorIDField = value;
                this.RaisePropertyChanged("ImportErrorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KeyType {
            get {
                return this.keyTypeField;
            }
            set {
                this.keyTypeField = value;
                this.RaisePropertyChanged("KeyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KeyValue {
            get {
                return this.keyValueField;
            }
            set {
                this.keyValueField = value;
                this.RaisePropertyChanged("KeyValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ErrorDate {
            get {
                return this.errorDateField;
            }
            set {
                this.errorDateField = value;
                this.RaisePropertyChanged("ErrorDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("Severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Procedure {
            get {
                return this.procedureField;
            }
            set {
                this.procedureField = value;
                this.RaisePropertyChanged("Procedure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
                this.RaisePropertyChanged("Line");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class ImportError : @__ImportError {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IAItemError))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__IAItemError : CustomObjectBase {
        
        private int itemErrorIDField;
        
        private System.Nullable<int> itemIDField;
        
        private System.DateTime errorDateField;
        
        private System.Nullable<int> numberField;
        
        private System.Nullable<int> severityField;
        
        private System.Nullable<int> stateField;
        
        private string procedureField;
        
        private System.Nullable<int> lineField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ItemErrorID {
            get {
                return this.itemErrorIDField;
            }
            set {
                this.itemErrorIDField = value;
                this.RaisePropertyChanged("ItemErrorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
                this.RaisePropertyChanged("ItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ErrorDate {
            get {
                return this.errorDateField;
            }
            set {
                this.errorDateField = value;
                this.RaisePropertyChanged("ErrorDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("Severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Procedure {
            get {
                return this.procedureField;
            }
            set {
                this.procedureField = value;
                this.RaisePropertyChanged("Procedure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
                this.RaisePropertyChanged("Line");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class IAItemError : @__IAItemError {
        
        private string iAIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IAIdentifier {
            get {
                return this.iAIdentifierField;
            }
            set {
                this.iAIdentifierField = value;
                this.RaisePropertyChanged("IAIdentifier");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BotanicusHarvestLog))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public abstract partial class @__BotanicusHarvestLog : CustomObjectBase {
        
        private int botanicusHarvestLogIDField;
        
        private System.DateTime harvestStartDateField;
        
        private System.DateTime harvestEndDateField;
        
        private bool automaticHarvestField;
        
        private bool successfulHarvestField;
        
        private int titleField;
        
        private int titleTagField;
        
        private int titleCreatorField;
        
        private int creatorField;
        
        private int itemField;
        
        private int pageField;
        
        private int indicatedPageField;
        
        private int pagePageTypeField;
        
        private int pageNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int BotanicusHarvestLogID {
            get {
                return this.botanicusHarvestLogIDField;
            }
            set {
                this.botanicusHarvestLogIDField = value;
                this.RaisePropertyChanged("BotanicusHarvestLogID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime HarvestStartDate {
            get {
                return this.harvestStartDateField;
            }
            set {
                this.harvestStartDateField = value;
                this.RaisePropertyChanged("HarvestStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime HarvestEndDate {
            get {
                return this.harvestEndDateField;
            }
            set {
                this.harvestEndDateField = value;
                this.RaisePropertyChanged("HarvestEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool AutomaticHarvest {
            get {
                return this.automaticHarvestField;
            }
            set {
                this.automaticHarvestField = value;
                this.RaisePropertyChanged("AutomaticHarvest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool SuccessfulHarvest {
            get {
                return this.successfulHarvestField;
            }
            set {
                this.successfulHarvestField = value;
                this.RaisePropertyChanged("SuccessfulHarvest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int TitleTag {
            get {
                return this.titleTagField;
            }
            set {
                this.titleTagField = value;
                this.RaisePropertyChanged("TitleTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TitleCreator {
            get {
                return this.titleCreatorField;
            }
            set {
                this.titleCreatorField = value;
                this.RaisePropertyChanged("TitleCreator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
                this.RaisePropertyChanged("Creator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
                this.RaisePropertyChanged("Page");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int IndicatedPage {
            get {
                return this.indicatedPageField;
            }
            set {
                this.indicatedPageField = value;
                this.RaisePropertyChanged("IndicatedPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int PagePageType {
            get {
                return this.pagePageTypeField;
            }
            set {
                this.pagePageTypeField = value;
                this.RaisePropertyChanged("PagePageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int PageName {
            get {
                return this.pageNameField;
            }
            set {
                this.pageNameField = value;
                this.RaisePropertyChanged("PageName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mobot.org/")]
    public partial class BotanicusHarvestLog : @__BotanicusHarvestLog {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BHLImportWSSoapChannel : MOBOT.BHL.AdminWeb.BHLImportWebService.BHLImportWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BHLImportWSSoapClient : System.ServiceModel.ClientBase<MOBOT.BHL.AdminWeb.BHLImportWebService.BHLImportWSSoap>, MOBOT.BHL.AdminWeb.BHLImportWebService.BHLImportWSSoap {
        
        public BHLImportWSSoapClient() {
        }
        
        public BHLImportWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BHLImportWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BHLImportWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BHLImportWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.IAItem[] IAItemSelectPendingApproval(int ageInDays) {
            return base.Channel.IAItemSelectPendingApproval(ageInDays);
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.BotanicusHarvestLog[] BotanicusHarvestLogSelectRecent(int numLogs) {
            return base.Channel.BotanicusHarvestLogSelectRecent(numLogs);
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.IAItemError[] IAItemErrorSelectRecent(int numErrors) {
            return base.Channel.IAItemErrorSelectRecent(numErrors);
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.ImportError[] ImportErrorSelectRecent(int numErrors) {
            return base.Channel.ImportErrorSelectRecent(numErrors);
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.ImportLog[] ImportLogSelectRecent(int numLogs) {
            return base.Channel.ImportLogSelectRecent(numLogs);
        }
        
        public string[] IAItemQueueForDownload(string iaIdentifier, string localFileFolder) {
            return base.Channel.IAItemQueueForDownload(iaIdentifier, localFileFolder);
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.IAItemStatus[] IAItemStatusSelectAll() {
            return base.Channel.IAItemStatusSelectAll();
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.IAItem[] IAItemSelectByStatus(int itemStatusId, int numberOfRows, int pageNumber, string sortColumn, string sortDirection) {
            return base.Channel.IAItemSelectByStatus(itemStatusId, numberOfRows, pageNumber, sortColumn, sortDirection);
        }
        
        public string[] IAItemUpdateStatus(int itemId, int itemStatusId) {
            return base.Channel.IAItemUpdateStatus(itemId, itemStatusId);
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.BSItemStatus[] BSItemStatusSelectAll() {
            return base.Channel.BSItemStatusSelectAll();
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.BSItem[] BSItemSelectByStatus(int itemStatusId, int numberOfRows, int pageNumber, string sortColumn, string sortDirection) {
            return base.Channel.BSItemSelectByStatus(itemStatusId, numberOfRows, pageNumber, sortColumn, sortDirection);
        }
        
        public string[] BSItemUpdateStatus(int itemId, int itemStatusId) {
            return base.Channel.BSItemUpdateStatus(itemId, itemStatusId);
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.BSSegment[] BSSegmentSelectByItem(int itemId) {
            return base.Channel.BSSegmentSelectByItem(itemId);
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.Stats[] StatsSelectReadyForProductionBySource(int importSourceID) {
            return base.Channel.StatsSelectReadyForProductionBySource(importSourceID);
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.Stats StatsCountIAItemPendingApproval(int ageInDays) {
            return base.Channel.StatsCountIAItemPendingApproval(ageInDays);
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.Stats[] StatsSelectIAItemGroupByStatus() {
            return base.Channel.StatsSelectIAItemGroupByStatus();
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.Stats[] StatsSelectIAItemPendingApprovalGroupByAge(int ageInDays) {
            return base.Channel.StatsSelectIAItemPendingApprovalGroupByAge(ageInDays);
        }
        
        public MOBOT.BHL.AdminWeb.BHLImportWebService.Stats[] StatsSelectBSItemGroupByStatus() {
            return base.Channel.StatsSelectBSItemGroupByStatus();
        }
    }
}
