CREATE PROCEDURE dbo.IAItemUpdateAuto

@ItemID INT,
@ItemStatusID INT,
@IAIdentifierPrefix NVARCHAR(50),
@IAIdentifier NVARCHAR(50),
@Sponsor NVARCHAR(100),
@SponsorName NVARCHAR(50),
@ScanningCenter NVARCHAR(50),
@CallNumber NVARCHAR(50),
@ImageCount INT,
@IdentifierAccessUrl NVARCHAR(100),
@Volume NVARCHAR(50),
@Note NVARCHAR(255),
@ScanOperator NVARCHAR(100),
@ScanDate NVARCHAR(50),
@ExternalStatus NVARCHAR(50),
@MARCBibID NVARCHAR(50),
@BarCode NVARCHAR(40),
@IADateStamp DATETIME,
@IAAddedDate DATETIME,
@LastOAIDataHarvestDate DATETIME,
@LastXMLDataHarvestDate DATETIME,
@LastProductionDate DATETIME,
@ShortTitle NVARCHAR(255),
@SponsorDate NVARCHAR(50),
@TitleID NVARCHAR(50),
@Year NVARCHAR(20),
@IdentifierBib NVARCHAR(50),
@ZQuery NVARCHAR(200),
@LicenseUrl NVARCHAR(MAX),
@Rights NVARCHAR(MAX),
@DueDiligence NVARCHAR(MAX),
@PossibleCopyrightStatus NVARCHAR(MAX),
@CopyrightRegion NVARCHAR(50),
@CopyrightComment NVARCHAR(MAX),
@CopyrightEvidence NVARCHAR(MAX),
@CopyrightEvidenceOperator NVARCHAR(100),
@CopyrightEvidenceDate NVARCHAR(30),
@LocalFileFolder NVARCHAR(200),
@NoMARCOk TINYINT,
@ScanningInstitution NVARCHAR(500),
@RightsHolder NVARCHAR(500),
@ItemDescription NVARCHAR(MAX)

AS 

SET NOCOUNT ON

UPDATE [dbo].[IAItem]
SET
	[ItemStatusID] = @ItemStatusID,
	[IAIdentifierPrefix] = @IAIdentifierPrefix,
	[IAIdentifier] = @IAIdentifier,
	[Sponsor] = @Sponsor,
	[SponsorName] = @SponsorName,
	[ScanningCenter] = @ScanningCenter,
	[CallNumber] = @CallNumber,
	[ImageCount] = @ImageCount,
	[IdentifierAccessUrl] = @IdentifierAccessUrl,
	[Volume] = @Volume,
	[Note] = @Note,
	[ScanOperator] = @ScanOperator,
	[ScanDate] = @ScanDate,
	[ExternalStatus] = @ExternalStatus,
	[MARCBibID] = @MARCBibID,
	[BarCode] = @BarCode,
	[IADateStamp] = @IADateStamp,
	[IAAddedDate] = @IAAddedDate,
	[LastOAIDataHarvestDate] = @LastOAIDataHarvestDate,
	[LastXMLDataHarvestDate] = @LastXMLDataHarvestDate,
	[LastProductionDate] = @LastProductionDate,
	[LastModifiedDate] = getdate(),
	[ShortTitle] = @ShortTitle,
	[SponsorDate] = @SponsorDate,
	[TitleID] = @TitleID,
	[Year] = @Year,
	[IdentifierBib] = @IdentifierBib,
	[ZQuery] = @ZQuery,
	[LicenseUrl] = @LicenseUrl,
	[Rights] = @Rights,
	[DueDiligence] = @DueDiligence,
	[PossibleCopyrightStatus] = @PossibleCopyrightStatus,
	[CopyrightRegion] = @CopyrightRegion,
	[CopyrightComment] = @CopyrightComment,
	[CopyrightEvidence] = @CopyrightEvidence,
	[CopyrightEvidenceOperator] = @CopyrightEvidenceOperator,
	[CopyrightEvidenceDate] = @CopyrightEvidenceDate,
	[LocalFileFolder] = @LocalFileFolder,
	[NoMARCOk] = @NoMARCOk,
	[ScanningInstitution] = @ScanningInstitution,
	[RightsHolder] = @RightsHolder,
	[ItemDescription] = @ItemDescription
WHERE
	[ItemID] = @ItemID
		
IF @@ERROR <> 0
BEGIN
	-- raiserror will throw a SqlException
	RAISERROR('An error occurred in procedure dbo.IAItemUpdateAuto. No information was updated as a result of this request.', 16, 1)
	RETURN 9 -- error occurred
END
ELSE BEGIN
	SELECT
		[ItemID],
		[ItemStatusID],
		[IAIdentifierPrefix],
		[IAIdentifier],
		[Sponsor],
		[SponsorName],
		[ScanningCenter],
		[CallNumber],
		[ImageCount],
		[IdentifierAccessUrl],
		[Volume],
		[Note],
		[ScanOperator],
		[ScanDate],
		[ExternalStatus],
		[MARCBibID],
		[BarCode],
		[IADateStamp],
		[IAAddedDate],
		[LastOAIDataHarvestDate],
		[LastXMLDataHarvestDate],
		[LastProductionDate],
		[CreatedDate],
		[LastModifiedDate],
		[ShortTitle],
		[SponsorDate],
		[TitleID],
		[Year],
		[IdentifierBib],
		[ZQuery],
		[LicenseUrl],
		[Rights],
		[DueDiligence],
		[PossibleCopyrightStatus],
		[CopyrightRegion],
		[CopyrightComment],
		[CopyrightEvidence],
		[CopyrightEvidenceOperator],
		[CopyrightEvidenceDate],
		[LocalFileFolder],
		[NoMARCOk],
		[ScanningInstitution],
		[RightsHolder],
		[ItemDescription]
	FROM [dbo].[IAItem]
	WHERE
		[ItemID] = @ItemID
	
	RETURN -- update successful
END
