
-- Insert Procedure for dbo.IAItem
-- Do not modify the contents of this procedure.
-- Generated 8/3/2016 12:50:45 PM

CREATE PROCEDURE dbo.IAItemInsertAuto

@ItemID INT OUTPUT,
@ItemStatusID INT,
@IAIdentifierPrefix NVARCHAR(50),
@IAIdentifier NVARCHAR(50),
@Sponsor NVARCHAR(100),
@SponsorName NVARCHAR(50) = null,
@ScanningCenter NVARCHAR(50),
@CallNumber NVARCHAR(50),
@ImageCount INT = null,
@IdentifierAccessUrl NVARCHAR(100) = null,
@Volume NVARCHAR(50),
@Note NVARCHAR(255),
@ScanOperator NVARCHAR(100),
@ScanDate NVARCHAR(50),
@ExternalStatus NVARCHAR(50),
@MARCBibID NVARCHAR(50),
@BarCode NVARCHAR(40),
@IADateStamp DATETIME = null,
@IAAddedDate DATETIME = null,
@LastOAIDataHarvestDate DATETIME = null,
@LastXMLDataHarvestDate DATETIME = null,
@LastProductionDate DATETIME = null,
@ShortTitle NVARCHAR(255) = null,
@SponsorDate NVARCHAR(50) = null,
@TitleID NVARCHAR(50),
@Year NVARCHAR(20),
@IdentifierBib NVARCHAR(50),
@ZQuery NVARCHAR(200),
@LicenseUrl NVARCHAR(MAX),
@Rights NVARCHAR(MAX),
@DueDiligence NVARCHAR(MAX),
@PossibleCopyrightStatus NVARCHAR(MAX),
@CopyrightRegion NVARCHAR(50),
@CopyrightComment NVARCHAR(MAX),
@CopyrightEvidence NVARCHAR(MAX),
@CopyrightEvidenceOperator NVARCHAR(100),
@CopyrightEvidenceDate NVARCHAR(30),
@LocalFileFolder NVARCHAR(200),
@NoMARCOk TINYINT,
@ScanningInstitution NVARCHAR(500),
@RightsHolder NVARCHAR(500)

AS 

SET NOCOUNT ON

INSERT INTO [dbo].[IAItem]
( 	[ItemStatusID],
	[IAIdentifierPrefix],
	[IAIdentifier],
	[Sponsor],
	[SponsorName],
	[ScanningCenter],
	[CallNumber],
	[ImageCount],
	[IdentifierAccessUrl],
	[Volume],
	[Note],
	[ScanOperator],
	[ScanDate],
	[ExternalStatus],
	[MARCBibID],
	[BarCode],
	[IADateStamp],
	[IAAddedDate],
	[LastOAIDataHarvestDate],
	[LastXMLDataHarvestDate],
	[LastProductionDate],
	[CreatedDate],
	[LastModifiedDate],
	[ShortTitle],
	[SponsorDate],
	[TitleID],
	[Year],
	[IdentifierBib],
	[ZQuery],
	[LicenseUrl],
	[Rights],
	[DueDiligence],
	[PossibleCopyrightStatus],
	[CopyrightRegion],
	[CopyrightComment],
	[CopyrightEvidence],
	[CopyrightEvidenceOperator],
	[CopyrightEvidenceDate],
	[LocalFileFolder],
	[NoMARCOk],
	[ScanningInstitution],
	[RightsHolder] )
VALUES
( 	@ItemStatusID,
	@IAIdentifierPrefix,
	@IAIdentifier,
	@Sponsor,
	@SponsorName,
	@ScanningCenter,
	@CallNumber,
	@ImageCount,
	@IdentifierAccessUrl,
	@Volume,
	@Note,
	@ScanOperator,
	@ScanDate,
	@ExternalStatus,
	@MARCBibID,
	@BarCode,
	@IADateStamp,
	@IAAddedDate,
	@LastOAIDataHarvestDate,
	@LastXMLDataHarvestDate,
	@LastProductionDate,
	getdate(),
	getdate(),
	@ShortTitle,
	@SponsorDate,
	@TitleID,
	@Year,
	@IdentifierBib,
	@ZQuery,
	@LicenseUrl,
	@Rights,
	@DueDiligence,
	@PossibleCopyrightStatus,
	@CopyrightRegion,
	@CopyrightComment,
	@CopyrightEvidence,
	@CopyrightEvidenceOperator,
	@CopyrightEvidenceDate,
	@LocalFileFolder,
	@NoMARCOk,
	@ScanningInstitution,
	@RightsHolder )

SET @ItemID = Scope_Identity()

IF @@ERROR <> 0
BEGIN
	-- raiserror will throw a SqlException
	RAISERROR('An error occurred in procedure dbo.IAItemInsertAuto. No information was inserted as a result of this request.', 16, 1)
	RETURN 9 -- error occurred
END
ELSE BEGIN
	SELECT
		[ItemID],
		[ItemStatusID],
		[IAIdentifierPrefix],
		[IAIdentifier],
		[Sponsor],
		[SponsorName],
		[ScanningCenter],
		[CallNumber],
		[ImageCount],
		[IdentifierAccessUrl],
		[Volume],
		[Note],
		[ScanOperator],
		[ScanDate],
		[ExternalStatus],
		[MARCBibID],
		[BarCode],
		[IADateStamp],
		[IAAddedDate],
		[LastOAIDataHarvestDate],
		[LastXMLDataHarvestDate],
		[LastProductionDate],
		[CreatedDate],
		[LastModifiedDate],
		[ShortTitle],
		[SponsorDate],
		[TitleID],
		[Year],
		[IdentifierBib],
		[ZQuery],
		[LicenseUrl],
		[Rights],
		[DueDiligence],
		[PossibleCopyrightStatus],
		[CopyrightRegion],
		[CopyrightComment],
		[CopyrightEvidence],
		[CopyrightEvidenceOperator],
		[CopyrightEvidenceDate],
		[LocalFileFolder],
		[NoMARCOk],
		[ScanningInstitution],
		[RightsHolder]	
	FROM [dbo].[IAItem]
	WHERE
		[ItemID] = @ItemID
	
	RETURN -- insert successful
END
