CREATE PROCEDURE dbo.ItemUpdateAuto

@ItemID INT,
@ImportKey NVARCHAR(50),
@ImportStatusID INT,
@ImportSourceID INT,
@MARCBibID NVARCHAR(50),
@BarCode NVARCHAR(200),
@ItemSequence SMALLINT,
@MARCItemID NVARCHAR(200),
@CallNumber NVARCHAR(100),
@Volume NVARCHAR(100),
@InstitutionCode NVARCHAR(10),
@LanguageCode NVARCHAR(10),
@Sponsor NVARCHAR(100),
@ItemDescription NTEXT,
@ScannedBy INT,
@PDFSize INT,
@VaultID INT,
@NumberOfFiles SMALLINT,
@Note NVARCHAR(255),
@ItemStatusID INT,
@ScanningUser NVARCHAR(100),
@ScanningDate DATETIME,
@PaginationCompleteUserID INT,
@PaginationCompleteDate DATETIME,
@PaginationStatusID INT,
@PaginationStatusUserID INT,
@PaginationStatusDate DATETIME,
@LastPageNameLookupDate DATETIME,
@ExternalCreationDate DATETIME,
@ExternalLastModifiedDate DATETIME,
@ExternalCreationUser INT,
@ExternalLastModifiedUser INT,
@ProductionDate DATETIME,
@Year NVARCHAR(20),
@IdentifierBib NVARCHAR(50),
@ZQuery NVARCHAR(200),
@LicenseUrl NVARCHAR(MAX),
@Rights NVARCHAR(MAX),
@DueDiligence NVARCHAR(MAX),
@CopyrightStatus NVARCHAR(MAX),
@CopyrightRegion NVARCHAR(50),
@CopyrightComment NVARCHAR(MAX),
@CopyrightEvidence NVARCHAR(MAX),
@CopyrightEvidenceOperator NVARCHAR(100),
@CopyrightEvidenceDate NVARCHAR(30),
@ScanningInstitutionCode NVARCHAR(10),
@RightsHolderCode NVARCHAR(10),
@EndYear NVARCHAR(20),
@StartVolume NVARCHAR(10),
@EndVolume NVARCHAR(10),
@StartIssue NVARCHAR(10),
@EndIssue NVARCHAR(10),
@StartNumber NVARCHAR(10),
@EndNumber NVARCHAR(10),
@StartSeries NVARCHAR(10),
@EndSeries NVARCHAR(10),
@StartPart NVARCHAR(10),
@EndPart NVARCHAR(10),
@PageProgression NVARCHAR(10),
@VirtualVolume NVARCHAR(100),
@VirtualTitleID INT,
@Summary NVARCHAR(MAX),
@SegmentGenreID INT,
@PublicationDetails NVARCHAR(400),
@PublisherName NVARCHAR(250),
@Issue NVARCHAR(100),
@SegmentDate NVARCHAR(20),
@StartPage NVARCHAR(20),
@EndPage NVARCHAR(20),
@Title NVARCHAR(2000),
@SortTitle NVARCHAR(2000),
@ContainerTitle NVARCHAR(2000)

AS 

SET NOCOUNT ON

UPDATE [dbo].[Item]
SET
	[ImportKey] = @ImportKey,
	[ImportStatusID] = @ImportStatusID,
	[ImportSourceID] = @ImportSourceID,
	[MARCBibID] = @MARCBibID,
	[BarCode] = @BarCode,
	[ItemSequence] = @ItemSequence,
	[MARCItemID] = @MARCItemID,
	[CallNumber] = @CallNumber,
	[Volume] = @Volume,
	[InstitutionCode] = @InstitutionCode,
	[LanguageCode] = @LanguageCode,
	[Sponsor] = @Sponsor,
	[ItemDescription] = @ItemDescription,
	[ScannedBy] = @ScannedBy,
	[PDFSize] = @PDFSize,
	[VaultID] = @VaultID,
	[NumberOfFiles] = @NumberOfFiles,
	[Note] = @Note,
	[ItemStatusID] = @ItemStatusID,
	[ScanningUser] = @ScanningUser,
	[ScanningDate] = @ScanningDate,
	[PaginationCompleteUserID] = @PaginationCompleteUserID,
	[PaginationCompleteDate] = @PaginationCompleteDate,
	[PaginationStatusID] = @PaginationStatusID,
	[PaginationStatusUserID] = @PaginationStatusUserID,
	[PaginationStatusDate] = @PaginationStatusDate,
	[LastPageNameLookupDate] = @LastPageNameLookupDate,
	[ExternalCreationDate] = @ExternalCreationDate,
	[ExternalLastModifiedDate] = @ExternalLastModifiedDate,
	[ExternalCreationUser] = @ExternalCreationUser,
	[ExternalLastModifiedUser] = @ExternalLastModifiedUser,
	[ProductionDate] = @ProductionDate,
	[LastModifiedDate] = getdate(),
	[Year] = @Year,
	[IdentifierBib] = @IdentifierBib,
	[ZQuery] = @ZQuery,
	[LicenseUrl] = @LicenseUrl,
	[Rights] = @Rights,
	[DueDiligence] = @DueDiligence,
	[CopyrightStatus] = @CopyrightStatus,
	[CopyrightRegion] = @CopyrightRegion,
	[CopyrightComment] = @CopyrightComment,
	[CopyrightEvidence] = @CopyrightEvidence,
	[CopyrightEvidenceOperator] = @CopyrightEvidenceOperator,
	[CopyrightEvidenceDate] = @CopyrightEvidenceDate,
	[ScanningInstitutionCode] = @ScanningInstitutionCode,
	[RightsHolderCode] = @RightsHolderCode,
	[EndYear] = @EndYear,
	[StartVolume] = @StartVolume,
	[EndVolume] = @EndVolume,
	[StartIssue] = @StartIssue,
	[EndIssue] = @EndIssue,
	[StartNumber] = @StartNumber,
	[EndNumber] = @EndNumber,
	[StartSeries] = @StartSeries,
	[EndSeries] = @EndSeries,
	[StartPart] = @StartPart,
	[EndPart] = @EndPart,
	[PageProgression] = @PageProgression,
	[VirtualVolume] = @VirtualVolume,
	[VirtualTitleID] = @VirtualTitleID,
	[Summary] = @Summary,
	[SegmentGenreID] = @SegmentGenreID,
	[PublicationDetails] = @PublicationDetails,
	[PublisherName] = @PublisherName,
	[Issue] = @Issue,
	[SegmentDate] = @SegmentDate,
	[StartPage] = @StartPage,
	[EndPage] = @EndPage,
	[Title] = @Title,
	[SortTitle] = @SortTitle,
	[ContainerTitle] = @ContainerTitle
WHERE
	[ItemID] = @ItemID
		
IF @@ERROR <> 0
BEGIN
	-- raiserror will throw a SqlException
	RAISERROR('An error occurred in procedure dbo.ItemUpdateAuto. No information was updated as a result of this request.', 16, 1)
	RETURN 9 -- error occurred
END
ELSE BEGIN
	SELECT
		[ItemID],
		[ImportKey],
		[ImportStatusID],
		[ImportSourceID],
		[MARCBibID],
		[BarCode],
		[ItemSequence],
		[MARCItemID],
		[CallNumber],
		[Volume],
		[InstitutionCode],
		[LanguageCode],
		[Sponsor],
		[ItemDescription],
		[ScannedBy],
		[PDFSize],
		[VaultID],
		[NumberOfFiles],
		[Note],
		[ItemStatusID],
		[ScanningUser],
		[ScanningDate],
		[PaginationCompleteUserID],
		[PaginationCompleteDate],
		[PaginationStatusID],
		[PaginationStatusUserID],
		[PaginationStatusDate],
		[LastPageNameLookupDate],
		[ExternalCreationDate],
		[ExternalLastModifiedDate],
		[ExternalCreationUser],
		[ExternalLastModifiedUser],
		[ProductionDate],
		[CreatedDate],
		[LastModifiedDate],
		[Year],
		[IdentifierBib],
		[ZQuery],
		[LicenseUrl],
		[Rights],
		[DueDiligence],
		[CopyrightStatus],
		[CopyrightRegion],
		[CopyrightComment],
		[CopyrightEvidence],
		[CopyrightEvidenceOperator],
		[CopyrightEvidenceDate],
		[ScanningInstitutionCode],
		[RightsHolderCode],
		[EndYear],
		[StartVolume],
		[EndVolume],
		[StartIssue],
		[EndIssue],
		[StartNumber],
		[EndNumber],
		[StartSeries],
		[EndSeries],
		[StartPart],
		[EndPart],
		[PageProgression],
		[VirtualVolume],
		[VirtualTitleID],
		[Summary],
		[SegmentGenreID],
		[PublicationDetails],
		[PublisherName],
		[Issue],
		[SegmentDate],
		[StartPage],
		[EndPage],
		[Title],
		[SortTitle],
		[ContainerTitle]
	FROM [dbo].[Item]
	WHERE
		[ItemID] = @ItemID
	
	RETURN -- update successful
END
GO
