//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOBOT.BHL.Web2.SiteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://biodiversitylibrary.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://biodiversitylibrary.org/", ConfigurationName="SiteService.SiteServiceSoap")]
    public interface SiteServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetOcrTextResult from namespace https://biodiversitylibrary.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://biodiversitylibrary.org/GetOcrText", ReplyAction="*")]
        MOBOT.BHL.Web2.SiteService.GetOcrTextResponse GetOcrText(MOBOT.BHL.Web2.SiteService.GetOcrTextRequest request);
        
        // CODEGEN: Generating message contract since element name batchId from namespace https://biodiversitylibrary.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://biodiversitylibrary.org/DOIGetFileContents", ReplyAction="*")]
        MOBOT.BHL.Web2.SiteService.DOIGetFileContentsResponse DOIGetFileContents(MOBOT.BHL.Web2.SiteService.DOIGetFileContentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://biodiversitylibrary.org/OcrJobExists", ReplyAction="*")]
        bool OcrJobExists(int itemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://biodiversitylibrary.org/OcrCreateJob", ReplyAction="*")]
        void OcrCreateJob(int itemID);
        
        // CODEGEN: Generating message contract since element name type from namespace https://biodiversitylibrary.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://biodiversitylibrary.org/MARCFileExists", ReplyAction="*")]
        MOBOT.BHL.Web2.SiteService.MARCFileExistsResponse MARCFileExists(MOBOT.BHL.Web2.SiteService.MARCFileExistsRequest request);
        
        // CODEGEN: Generating message contract since element name type from namespace https://biodiversitylibrary.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://biodiversitylibrary.org/MARCGetFileContents", ReplyAction="*")]
        MOBOT.BHL.Web2.SiteService.MARCGetFileContentsResponse MARCGetFileContents(MOBOT.BHL.Web2.SiteService.MARCGetFileContentsRequest request);
        
        // CODEGEN: Generating message contract since element name marcBibID from namespace https://biodiversitylibrary.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://biodiversitylibrary.org/MarcCreateFile", ReplyAction="*")]
        MOBOT.BHL.Web2.SiteService.MarcCreateFileResponse MarcCreateFile(MOBOT.BHL.Web2.SiteService.MarcCreateFileRequest request);
        
        // CODEGEN: Generating message contract since element name from from namespace https://biodiversitylibrary.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://biodiversitylibrary.org/SendEmail", ReplyAction="*")]
        MOBOT.BHL.Web2.SiteService.SendEmailResponse SendEmail(MOBOT.BHL.Web2.SiteService.SendEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOcrTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOcrText", Namespace="https://biodiversitylibrary.org/", Order=0)]
        public MOBOT.BHL.Web2.SiteService.GetOcrTextRequestBody Body;
        
        public GetOcrTextRequest() {
        }
        
        public GetOcrTextRequest(MOBOT.BHL.Web2.SiteService.GetOcrTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://biodiversitylibrary.org/")]
    public partial class GetOcrTextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pageID;
        
        public GetOcrTextRequestBody() {
        }
        
        public GetOcrTextRequestBody(int pageID) {
            this.pageID = pageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOcrTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOcrTextResponse", Namespace="https://biodiversitylibrary.org/", Order=0)]
        public MOBOT.BHL.Web2.SiteService.GetOcrTextResponseBody Body;
        
        public GetOcrTextResponse() {
        }
        
        public GetOcrTextResponse(MOBOT.BHL.Web2.SiteService.GetOcrTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://biodiversitylibrary.org/")]
    public partial class GetOcrTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOcrTextResult;
        
        public GetOcrTextResponseBody() {
        }
        
        public GetOcrTextResponseBody(string GetOcrTextResult) {
            this.GetOcrTextResult = GetOcrTextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DOIGetFileContentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DOIGetFileContents", Namespace="https://biodiversitylibrary.org/", Order=0)]
        public MOBOT.BHL.Web2.SiteService.DOIGetFileContentsRequestBody Body;
        
        public DOIGetFileContentsRequest() {
        }
        
        public DOIGetFileContentsRequest(MOBOT.BHL.Web2.SiteService.DOIGetFileContentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://biodiversitylibrary.org/")]
    public partial class DOIGetFileContentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string batchId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        public DOIGetFileContentsRequestBody() {
        }
        
        public DOIGetFileContentsRequestBody(string batchId, string type) {
            this.batchId = batchId;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DOIGetFileContentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DOIGetFileContentsResponse", Namespace="https://biodiversitylibrary.org/", Order=0)]
        public MOBOT.BHL.Web2.SiteService.DOIGetFileContentsResponseBody Body;
        
        public DOIGetFileContentsResponse() {
        }
        
        public DOIGetFileContentsResponse(MOBOT.BHL.Web2.SiteService.DOIGetFileContentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://biodiversitylibrary.org/")]
    public partial class DOIGetFileContentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DOIGetFileContentsResult;
        
        public DOIGetFileContentsResponseBody() {
        }
        
        public DOIGetFileContentsResponseBody(string DOIGetFileContentsResult) {
            this.DOIGetFileContentsResult = DOIGetFileContentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MARCFileExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MARCFileExists", Namespace="https://biodiversitylibrary.org/", Order=0)]
        public MOBOT.BHL.Web2.SiteService.MARCFileExistsRequestBody Body;
        
        public MARCFileExistsRequest() {
        }
        
        public MARCFileExistsRequest(MOBOT.BHL.Web2.SiteService.MARCFileExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://biodiversitylibrary.org/")]
    public partial class MARCFileExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        public MARCFileExistsRequestBody() {
        }
        
        public MARCFileExistsRequestBody(int id, string type) {
            this.id = id;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MARCFileExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MARCFileExistsResponse", Namespace="https://biodiversitylibrary.org/", Order=0)]
        public MOBOT.BHL.Web2.SiteService.MARCFileExistsResponseBody Body;
        
        public MARCFileExistsResponse() {
        }
        
        public MARCFileExistsResponse(MOBOT.BHL.Web2.SiteService.MARCFileExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://biodiversitylibrary.org/")]
    public partial class MARCFileExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MARCFileExistsResult;
        
        public MARCFileExistsResponseBody() {
        }
        
        public MARCFileExistsResponseBody(bool MARCFileExistsResult) {
            this.MARCFileExistsResult = MARCFileExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MARCGetFileContentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MARCGetFileContents", Namespace="https://biodiversitylibrary.org/", Order=0)]
        public MOBOT.BHL.Web2.SiteService.MARCGetFileContentsRequestBody Body;
        
        public MARCGetFileContentsRequest() {
        }
        
        public MARCGetFileContentsRequest(MOBOT.BHL.Web2.SiteService.MARCGetFileContentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://biodiversitylibrary.org/")]
    public partial class MARCGetFileContentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        public MARCGetFileContentsRequestBody() {
        }
        
        public MARCGetFileContentsRequestBody(int id, string type) {
            this.id = id;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MARCGetFileContentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MARCGetFileContentsResponse", Namespace="https://biodiversitylibrary.org/", Order=0)]
        public MOBOT.BHL.Web2.SiteService.MARCGetFileContentsResponseBody Body;
        
        public MARCGetFileContentsResponse() {
        }
        
        public MARCGetFileContentsResponse(MOBOT.BHL.Web2.SiteService.MARCGetFileContentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://biodiversitylibrary.org/")]
    public partial class MARCGetFileContentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MARCGetFileContentsResult;
        
        public MARCGetFileContentsResponseBody() {
        }
        
        public MARCGetFileContentsResponseBody(string MARCGetFileContentsResult) {
            this.MARCGetFileContentsResult = MARCGetFileContentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarcCreateFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarcCreateFile", Namespace="https://biodiversitylibrary.org/", Order=0)]
        public MOBOT.BHL.Web2.SiteService.MarcCreateFileRequestBody Body;
        
        public MarcCreateFileRequest() {
        }
        
        public MarcCreateFileRequest(MOBOT.BHL.Web2.SiteService.MarcCreateFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://biodiversitylibrary.org/")]
    public partial class MarcCreateFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string marcBibID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        public MarcCreateFileRequestBody() {
        }
        
        public MarcCreateFileRequestBody(string marcBibID, string content) {
            this.marcBibID = marcBibID;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarcCreateFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarcCreateFileResponse", Namespace="https://biodiversitylibrary.org/", Order=0)]
        public MOBOT.BHL.Web2.SiteService.MarcCreateFileResponseBody Body;
        
        public MarcCreateFileResponse() {
        }
        
        public MarcCreateFileResponse(MOBOT.BHL.Web2.SiteService.MarcCreateFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MarcCreateFileResponseBody {
        
        public MarcCreateFileResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmail", Namespace="https://biodiversitylibrary.org/", Order=0)]
        public MOBOT.BHL.Web2.SiteService.SendEmailRequestBody Body;
        
        public SendEmailRequest() {
        }
        
        public SendEmailRequest(MOBOT.BHL.Web2.SiteService.SendEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://biodiversitylibrary.org/")]
    public partial class SendEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MOBOT.BHL.Web2.SiteService.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MOBOT.BHL.Web2.SiteService.ArrayOfString cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public MOBOT.BHL.Web2.SiteService.ArrayOfString bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string body;
        
        public SendEmailRequestBody() {
        }
        
        public SendEmailRequestBody(string from, MOBOT.BHL.Web2.SiteService.ArrayOfString to, MOBOT.BHL.Web2.SiteService.ArrayOfString cc, MOBOT.BHL.Web2.SiteService.ArrayOfString bcc, string subject, string body) {
            this.from = from;
            this.to = to;
            this.cc = cc;
            this.bcc = bcc;
            this.subject = subject;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailResponse", Namespace="https://biodiversitylibrary.org/", Order=0)]
        public MOBOT.BHL.Web2.SiteService.SendEmailResponseBody Body;
        
        public SendEmailResponse() {
        }
        
        public SendEmailResponse(MOBOT.BHL.Web2.SiteService.SendEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://biodiversitylibrary.org/")]
    public partial class SendEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendEmailResult;
        
        public SendEmailResponseBody() {
        }
        
        public SendEmailResponseBody(bool SendEmailResult) {
            this.SendEmailResult = SendEmailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SiteServiceSoapChannel : MOBOT.BHL.Web2.SiteService.SiteServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiteServiceSoapClient : System.ServiceModel.ClientBase<MOBOT.BHL.Web2.SiteService.SiteServiceSoap>, MOBOT.BHL.Web2.SiteService.SiteServiceSoap {
        
        public SiteServiceSoapClient() {
        }
        
        public SiteServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiteServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOBOT.BHL.Web2.SiteService.GetOcrTextResponse MOBOT.BHL.Web2.SiteService.SiteServiceSoap.GetOcrText(MOBOT.BHL.Web2.SiteService.GetOcrTextRequest request) {
            return base.Channel.GetOcrText(request);
        }
        
        public string GetOcrText(int pageID) {
            MOBOT.BHL.Web2.SiteService.GetOcrTextRequest inValue = new MOBOT.BHL.Web2.SiteService.GetOcrTextRequest();
            inValue.Body = new MOBOT.BHL.Web2.SiteService.GetOcrTextRequestBody();
            inValue.Body.pageID = pageID;
            MOBOT.BHL.Web2.SiteService.GetOcrTextResponse retVal = ((MOBOT.BHL.Web2.SiteService.SiteServiceSoap)(this)).GetOcrText(inValue);
            return retVal.Body.GetOcrTextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOBOT.BHL.Web2.SiteService.DOIGetFileContentsResponse MOBOT.BHL.Web2.SiteService.SiteServiceSoap.DOIGetFileContents(MOBOT.BHL.Web2.SiteService.DOIGetFileContentsRequest request) {
            return base.Channel.DOIGetFileContents(request);
        }
        
        public string DOIGetFileContents(string batchId, string type) {
            MOBOT.BHL.Web2.SiteService.DOIGetFileContentsRequest inValue = new MOBOT.BHL.Web2.SiteService.DOIGetFileContentsRequest();
            inValue.Body = new MOBOT.BHL.Web2.SiteService.DOIGetFileContentsRequestBody();
            inValue.Body.batchId = batchId;
            inValue.Body.type = type;
            MOBOT.BHL.Web2.SiteService.DOIGetFileContentsResponse retVal = ((MOBOT.BHL.Web2.SiteService.SiteServiceSoap)(this)).DOIGetFileContents(inValue);
            return retVal.Body.DOIGetFileContentsResult;
        }
        
        public bool OcrJobExists(int itemID) {
            return base.Channel.OcrJobExists(itemID);
        }
        
        public void OcrCreateJob(int itemID) {
            base.Channel.OcrCreateJob(itemID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOBOT.BHL.Web2.SiteService.MARCFileExistsResponse MOBOT.BHL.Web2.SiteService.SiteServiceSoap.MARCFileExists(MOBOT.BHL.Web2.SiteService.MARCFileExistsRequest request) {
            return base.Channel.MARCFileExists(request);
        }
        
        public bool MARCFileExists(int id, string type) {
            MOBOT.BHL.Web2.SiteService.MARCFileExistsRequest inValue = new MOBOT.BHL.Web2.SiteService.MARCFileExistsRequest();
            inValue.Body = new MOBOT.BHL.Web2.SiteService.MARCFileExistsRequestBody();
            inValue.Body.id = id;
            inValue.Body.type = type;
            MOBOT.BHL.Web2.SiteService.MARCFileExistsResponse retVal = ((MOBOT.BHL.Web2.SiteService.SiteServiceSoap)(this)).MARCFileExists(inValue);
            return retVal.Body.MARCFileExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOBOT.BHL.Web2.SiteService.MARCGetFileContentsResponse MOBOT.BHL.Web2.SiteService.SiteServiceSoap.MARCGetFileContents(MOBOT.BHL.Web2.SiteService.MARCGetFileContentsRequest request) {
            return base.Channel.MARCGetFileContents(request);
        }
        
        public string MARCGetFileContents(int id, string type) {
            MOBOT.BHL.Web2.SiteService.MARCGetFileContentsRequest inValue = new MOBOT.BHL.Web2.SiteService.MARCGetFileContentsRequest();
            inValue.Body = new MOBOT.BHL.Web2.SiteService.MARCGetFileContentsRequestBody();
            inValue.Body.id = id;
            inValue.Body.type = type;
            MOBOT.BHL.Web2.SiteService.MARCGetFileContentsResponse retVal = ((MOBOT.BHL.Web2.SiteService.SiteServiceSoap)(this)).MARCGetFileContents(inValue);
            return retVal.Body.MARCGetFileContentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOBOT.BHL.Web2.SiteService.MarcCreateFileResponse MOBOT.BHL.Web2.SiteService.SiteServiceSoap.MarcCreateFile(MOBOT.BHL.Web2.SiteService.MarcCreateFileRequest request) {
            return base.Channel.MarcCreateFile(request);
        }
        
        public void MarcCreateFile(string marcBibID, string content) {
            MOBOT.BHL.Web2.SiteService.MarcCreateFileRequest inValue = new MOBOT.BHL.Web2.SiteService.MarcCreateFileRequest();
            inValue.Body = new MOBOT.BHL.Web2.SiteService.MarcCreateFileRequestBody();
            inValue.Body.marcBibID = marcBibID;
            inValue.Body.content = content;
            MOBOT.BHL.Web2.SiteService.MarcCreateFileResponse retVal = ((MOBOT.BHL.Web2.SiteService.SiteServiceSoap)(this)).MarcCreateFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOBOT.BHL.Web2.SiteService.SendEmailResponse MOBOT.BHL.Web2.SiteService.SiteServiceSoap.SendEmail(MOBOT.BHL.Web2.SiteService.SendEmailRequest request) {
            return base.Channel.SendEmail(request);
        }
        
        public bool SendEmail(string from, MOBOT.BHL.Web2.SiteService.ArrayOfString to, MOBOT.BHL.Web2.SiteService.ArrayOfString cc, MOBOT.BHL.Web2.SiteService.ArrayOfString bcc, string subject, string body) {
            MOBOT.BHL.Web2.SiteService.SendEmailRequest inValue = new MOBOT.BHL.Web2.SiteService.SendEmailRequest();
            inValue.Body = new MOBOT.BHL.Web2.SiteService.SendEmailRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            MOBOT.BHL.Web2.SiteService.SendEmailResponse retVal = ((MOBOT.BHL.Web2.SiteService.SiteServiceSoap)(this)).SendEmail(inValue);
            return retVal.Body.SendEmailResult;
        }
    }
}
