CREATE PROCEDURE [dbo].[ItemInsertAuto]

@ItemID INT OUTPUT,
@PrimaryTitleID INT,
@BarCode NVARCHAR(40),
@MARCItemID NVARCHAR(50) = null,
@CallNumber NVARCHAR(100) = null,
@Volume NVARCHAR(100) = null,
@InstitutionCode NVARCHAR(10) = null,
@LanguageCode NVARCHAR(10) = null,
@ItemDescription NTEXT = null,
@ScannedBy INT = null,
@PDFSize INT = null,
@VaultID INT = null,
@NumberOfFiles SMALLINT = null,
@Note NVARCHAR(255) = null,
@CreationUserID INT = null,
@LastModifiedUserID INT = null,
@ItemStatusID INT,
@ScanningUser NVARCHAR(100) = null,
@ScanningDate DATETIME = null,
@PaginationCompleteUserID INT = null,
@PaginationCompleteDate DATETIME = null,
@PaginationStatusID INT = null,
@PaginationStatusUserID INT = null,
@PaginationStatusDate DATETIME = null,
@LastPageNameLookupDate DATETIME = null,
@ItemSourceID INT = null,
@Year NVARCHAR(20) = null,
@IdentifierBib NVARCHAR(50) = null,
@FileRootFolder NVARCHAR(250) = null,
@ZQuery NVARCHAR(200) = null,
@Sponsor NVARCHAR(100) = null,
@LicenseUrl NVARCHAR(MAX) = null,
@Rights NVARCHAR(MAX) = null,
@DueDiligence NVARCHAR(MAX) = null,
@CopyrightStatus NVARCHAR(MAX) = null,
@CopyrightRegion NVARCHAR(50) = null,
@CopyrightComment NVARCHAR(MAX) = null,
@CopyrightEvidence NVARCHAR(MAX) = null,
@CopyrightEvidenceOperator NVARCHAR(100) = null,
@CopyrightEvidenceDate NVARCHAR(30) = null,
@ThumbnailPageID INT = null,
@RedirectItemID INT = null,
@ExternalUrl NVARCHAR(500) = null,
@EndYear NVARCHAR(20),
@StartVolume NVARCHAR(10),
@EndVolume NVARCHAR(10),
@StartIssue NVARCHAR(10),
@EndIssue NVARCHAR(10),
@StartNumber NVARCHAR(10),
@EndNumber NVARCHAR(10),
@StartSeries NVARCHAR(10),
@EndSeries NVARCHAR(10),
@StartPart NVARCHAR(10),
@EndPart NVARCHAR(10),
@VolumeReviewed TINYINT,
@VolumeReviewedDate DATETIME = null,
@VolumeReviewedUserID INT = null

AS 

SET NOCOUNT ON

INSERT INTO [dbo].[Item]
( 	[PrimaryTitleID],
	[BarCode],
	[MARCItemID],
	[CallNumber],
	[Volume],
	[InstitutionCode],
	[LanguageCode],
	[ItemDescription],
	[ScannedBy],
	[PDFSize],
	[VaultID],
	[NumberOfFiles],
	[Note],
	[CreationDate],
	[LastModifiedDate],
	[CreationUserID],
	[LastModifiedUserID],
	[ItemStatusID],
	[ScanningUser],
	[ScanningDate],
	[PaginationCompleteUserID],
	[PaginationCompleteDate],
	[PaginationStatusID],
	[PaginationStatusUserID],
	[PaginationStatusDate],
	[LastPageNameLookupDate],
	[ItemSourceID],
	[Year],
	[IdentifierBib],
	[FileRootFolder],
	[ZQuery],
	[Sponsor],
	[LicenseUrl],
	[Rights],
	[DueDiligence],
	[CopyrightStatus],
	[CopyrightRegion],
	[CopyrightComment],
	[CopyrightEvidence],
	[CopyrightEvidenceOperator],
	[CopyrightEvidenceDate],
	[ThumbnailPageID],
	[RedirectItemID],
	[ExternalUrl],
	[EndYear],
	[StartVolume],
	[EndVolume],
	[StartIssue],
	[EndIssue],
	[StartNumber],
	[EndNumber],
	[StartSeries],
	[EndSeries],
	[StartPart],
	[EndPart],
	[VolumeReviewed],
	[VolumeReviewedDate],
	[VolumeReviewedUserID] )
VALUES
( 	@PrimaryTitleID,
	@BarCode,
	@MARCItemID,
	@CallNumber,
	@Volume,
	@InstitutionCode,
	@LanguageCode,
	@ItemDescription,
	@ScannedBy,
	@PDFSize,
	@VaultID,
	@NumberOfFiles,
	@Note,
	getdate(),
	getdate(),
	@CreationUserID,
	@LastModifiedUserID,
	@ItemStatusID,
	@ScanningUser,
	@ScanningDate,
	@PaginationCompleteUserID,
	@PaginationCompleteDate,
	@PaginationStatusID,
	@PaginationStatusUserID,
	@PaginationStatusDate,
	@LastPageNameLookupDate,
	@ItemSourceID,
	@Year,
	@IdentifierBib,
	@FileRootFolder,
	@ZQuery,
	@Sponsor,
	@LicenseUrl,
	@Rights,
	@DueDiligence,
	@CopyrightStatus,
	@CopyrightRegion,
	@CopyrightComment,
	@CopyrightEvidence,
	@CopyrightEvidenceOperator,
	@CopyrightEvidenceDate,
	@ThumbnailPageID,
	@RedirectItemID,
	@ExternalUrl,
	@EndYear,
	@StartVolume,
	@EndVolume,
	@StartIssue,
	@EndIssue,
	@StartNumber,
	@EndNumber,
	@StartSeries,
	@EndSeries,
	@StartPart,
	@EndPart,
	@VolumeReviewed,
	@VolumeReviewedDate,
	@VolumeReviewedUserID )

SET @ItemID = Scope_Identity()

IF @@ERROR <> 0
BEGIN
	-- raiserror will throw a SqlException
	RAISERROR('An error occurred in procedure dbo.ItemInsertAuto. No information was inserted as a result of this request.', 16, 1)
	RETURN 9 -- error occurred
END
ELSE BEGIN
	SELECT
		[ItemID],
		[PrimaryTitleID],
		[BarCode],
		[MARCItemID],
		[CallNumber],
		[Volume],
		[InstitutionCode],
		[LanguageCode],
		[ItemDescription],
		[ScannedBy],
		[PDFSize],
		[VaultID],
		[NumberOfFiles],
		[Note],
		[CreationDate],
		[LastModifiedDate],
		[CreationUserID],
		[LastModifiedUserID],
		[ItemStatusID],
		[ScanningUser],
		[ScanningDate],
		[PaginationCompleteUserID],
		[PaginationCompleteDate],
		[PaginationStatusID],
		[PaginationStatusUserID],
		[PaginationStatusDate],
		[LastPageNameLookupDate],
		[ItemSourceID],
		[Year],
		[IdentifierBib],
		[FileRootFolder],
		[ZQuery],
		[Sponsor],
		[LicenseUrl],
		[Rights],
		[DueDiligence],
		[CopyrightStatus],
		[CopyrightRegion],
		[CopyrightComment],
		[CopyrightEvidence],
		[CopyrightEvidenceOperator],
		[CopyrightEvidenceDate],
		[ThumbnailPageID],
		[RedirectItemID],
		[ExternalUrl],
		[EndYear],
		[StartVolume],
		[EndVolume],
		[StartIssue],
		[EndIssue],
		[StartNumber],
		[EndNumber],
		[StartSeries],
		[EndSeries],
		[StartPart],
		[EndPart],
		[VolumeReviewed],
		[VolumeReviewedDate],
		[VolumeReviewedUserID]	
	FROM [dbo].[Item]
	WHERE
		[ItemID] = @ItemID
	
	RETURN -- insert successful
END
