CREATE PROCEDURE [dbo].[MonthlyStatsUpdate]
AS
BEGIN

SET NOCOUNT ON

CREATE TABLE #tmpMonthlyStats
	(
	[Year] int NULL,
	[Month] int NULL,
	[InstitutionCode] nvarchar(10) NULL,
	[StatType] nvarchar(100) NULL,
	[StatValue] int NULL
	)

/*
-- Titles by institution
INSERT	#tmpMonthlyStats
SELECT	[Year], 
		[Month], 
		'N/A', 
		'Titles Created', 
		COUNT(*)
FROM	(
		SELECT DISTINCT 
			titleid,
			DATEPART(year, CreationDate) AS [Year],
			DATEPART(month, CreationDate) AS [Month]
		FROM dbo.Title
		WHERE publishready = 1
		) x
GROUP BY [Year], [Month]
*/

-- Items by institution
INSERT	#tmpMonthlyStats
SELECT	DATEPART(year, i.CreationDate) AS [Year],
		DATEPART(month, i.CreationDate) AS [Month],
		ii.InstitutionCode,
		'Items Created',
		COUNT(*)
FROM	dbo.Item i 
		INNER JOIN dbo.ItemInstitution ii ON i.ItemID = ii.ItemID
WHERE	i.ItemStatusID = 40
GROUP BY
		DATEPART(year, i.CreationDate),
		DATEPART(month, i.CreationDate),
		ii.InstitutionCode

/*
-- Items scanned by institution
INSERT	#tmpMonthlyStats
SELECT	DATEPART(year, i.ScanningDate) AS [Year],
		DATEPART(month, i.ScanningDate) AS [Month],
		ii.InstitutionCode,
		'Items Scanned',
		COUNT(*)
FROM	dbo.Item i 
		INNER JOIN dbo.ItemInstitution ii ON i.ItemID = ii.ItemID
WHERE	i.ItemStatusID = 40
GROUP BY
		DATEPART(year, i.ScanningDate),
		DATEPART(month, i.ScanningDate),
		ii.InstitutionCode
*/

-- Pages by institution
INSERT	#tmpMonthlyStats
SELECT 	DATEPART(year, p.CreationDate) AS [Year],
		DATEPART(month, p.CreationDate) AS [Month],
		ii.InstitutionCode,
		'Pages Created',
		COUNT(*)
FROM	dbo.Item i 
		INNER JOIN dbo.ItemInstitution ii ON i.ItemID = ii.ItemID
		INNER JOIN dbo.Page p ON i.itemid = p.itemid
WHERE	itemstatusid = 40
AND		p.active = 1
GROUP BY DATEPART(year, p.CreationDate),
		DATEPART(month, p.CreationDate),
		ii.InstitutionCode

-- Pagenames by institution
INSERT	#tmpMonthlyStats
SELECT	DATEPART(year, np.CreationDate) AS [Year],
		DATEPART(month, np.CreationDate) AS [Month],
		ii.InstitutionCode,
		'PageNames Created',
		COUNT(*)
FROM	dbo.Item i 
		INNER JOIN dbo.ItemInstitution ii ON i.ItemID = ii.ItemID
		INNER JOIN dbo.Page p ON i.itemid = p.itemid
		INNER JOIN dbo.NamePage np ON p.pageid = np.pageid
WHERE	itemstatusid = 40
AND		p.active = 1
GROUP BY DATEPART(year, np.CreationDate),
		DATEPART(month, np.CreationDate),
		ii.InstitutionCode

-- Segments by institution
INSERT	#tmpMonthlyStats
SELECT	DATEPART(year, s.CreationDate) AS [Year],
		DATEPART(month, s.CreationDate) AS [Month],
		si.InstitutionCode,
		'Segments Created',
		COUNT(*)
FROM	dbo.Segment s 
		INNER JOIN dbo.SegmentInstitution si ON s.SegmentID = si.SegmentID
WHERE	SegmentStatusID IN (10, 20) -- New, Published
GROUP BY
		DATEPART(year, s.CreationDate),
		DATEPART(month, s.CreationDate),
		si.InstitutionCode

-- PDFs generated by month
INSERT	#tmpMonthlyStats
SELECT	DATEPART(year, CreationDate) AS [Year],
		DATEPART(month, CreationDate) AS [Month],
		'N/A',
		'PDFs Created',
		COUNT(*)
FROM	dbo.PDF 
WHERE	PDFStatusID = 30
GROUP BY
		DATEPART(year, CreationDate),
		DATEPART(month, CreationDate)

-- DOIs assigned by month
INSERT	#tmpMonthlyStats
SELECT	DATEPART(year, CreationDate) AS [Year],
		DATEPART(month, CreationDate) AS [Month],
		'N/A',
		'DOIs Created',
		COUNT(*)
FROM	dbo.DOI 
WHERE	DOIStatusID = 100
GROUP BY
		DATEPART(year, CreationDate),
		DATEPART(month, CreationDate)


UPDATE	#tmpMonthlyStats
SET		[Year] = ISNULL([Year], 0),
		[Month] = ISNULL([Month], 0),
		InstitutionCode = ISNULL(InstitutionCode, '')

TRUNCATE TABLE dbo.MonthlyStats

INSERT	dbo.MonthlyStats
SELECT	[Year],
		[Month],
		InstitutionCode,
		StatType,
		StatValue,
		GETDATE(),
		GETDATE()
FROM	#tmpMonthlyStats

END
