
CREATE Procedure [dbo].[TitleSearchCount]
	@MARCBibID nvarchar(50),
	@TitleID int,
	@Title nvarchar(60)
AS

DECLARE @spName varchar(300) 

SET @spName = 'TitleSearchPaging_AutoGen_'
SET @spName = @spName + CASE COALESCE(@MARCBibID, '0') WHEN '0' THEN '0' ELSE '1' END
SET @spName = @spName + CASE COALESCE(@TitleID, '0') WHEN '0' THEN '0' ELSE '1' END
SET @spName = @spName + CASE COALESCE(@Title, '0') WHEN '0' THEN '0' ELSE '1' END

IF EXISTS (SELECT * from dbo.sysobjects where id = object_id(N'[dbo].' + @spName) and OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
	--Print 'Skipping to execution of ' + @spName
	GOTO executeProcedure
END
ELSE
BEGIN
	--Print 'Building Stored Procedure ' + @spName
	BEGIN TRAN

	DECLARE @SQL varchar(4000)
	DECLARE @WhereClause varchar(2500)
	DECLARE @WhereItem int

	SET @WhereItem = 0
	SET @WhereClause = 'WHERE '		

	SET @SQL = 'CREATE PROCEDURE [dbo].' + @spName + '
	@MarcBIBID nvarchar(50),
	@TitleID int,
	@Title nvarchar(60)
AS
/******************************************************************************
**		Name: ' + @spName + '
**		Desc: This is an auto generated stored procedure. DO NOT CHANGE
**          Auto generated by TitleSearchCount stored procedure.
**		Date: ' + CONVERT(varchar(30), GetDate()) + '
*******************************************************************************/

SELECT COUNT(*) FROM dbo.Title T '

	IF @MarcBibID IS NOT NULL 
	BEGIN
		SET @WhereClause = @WhereClause + 'T.MarcBibID COLLATE latin1_general_ci_ai LIKE @MarcBibID AND '
	END

	IF @TitleID IS NOT NULL
	BEGIN
		SET @WhereClause = @WhereClause + 'T.TitleID = @TitleID AND '
	END
	IF @Title IS NOT NULL
	BEGIN
		SET @WhereClause = @WhereClause + 'T.SortTitle COLLATE latin1_general_ci_ai LIKE @Title AND '
	END

	SET @Sql = @Sql + @WhereClause
	IF LEN(@WhereClause) > 6 
	BEGIN
		SET @Sql = LEFT(@Sql, LEN(@SQL) - 4 )
	END
	ELSE
	BEGIN
		SET @Sql = LEFT( @Sql, LEN(@Sql) - 6 )
	END

	Print 'SQL for Stored Procedure: ' + @SQL

	EXEC(@Sql)

	SET @Sql = ' GRANT EXEC ON [dbo].' + @spName + ' TO PUBLIC ' + 
	'	GRANT EXEC ON [dbo].' + @spName + ' TO BHLWebUser ' 

	EXEC(@Sql)

	COMMIT

	END

executeProcedure:
	EXEC @spName @MarcBibID, @TitleID, @Title


